CREATE SCHEMA "yugioh_data";
--> statement-breakpoint
CREATE SCHEMA "yugioh";
--> statement-breakpoint
CREATE TYPE "yugioh_data"."import_batch_status" AS ENUM('running', 'completed', 'completed_with_errors', 'failed', 'interrupted');--> statement-breakpoint
CREATE TYPE "yugioh_data"."publish_batch_row_action" AS ENUM('insert', 'update', 'unchanged');--> statement-breakpoint
CREATE TYPE "yugioh_data"."publish_batch_row_status" AS ENUM('pending', 'applied', 'skipped', 'failed');--> statement-breakpoint
CREATE TYPE "yugioh_data"."publish_batch_status" AS ENUM('planning', 'applying', 'completed', 'failed');--> statement-breakpoint
CREATE TABLE "yugioh"."cards" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "yugioh"."yugioh_cards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"cid" bigint,
	"password" varchar(8),
	"cn_name" text,
	"sc_name" text,
	"md_name" text,
	"nwbbs_name" text,
	"cnocg_name" text,
	"jp_ruby" text,
	"jp_name" text,
	"en_name" text,
	"md_en_name" text,
	"wiki_en_name" text,
	"set_ext" text,
	"types_text" text,
	"pendulum_description" text,
	"description" text,
	"ot" integer,
	"setcode" bigint,
	"type" bigint,
	"attack" integer,
	"defense" integer,
	"level" integer,
	"race" bigint,
	"attribute" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "cards_cid_positive_chk" CHECK ("cid" is null or "cid" > 0),
	CONSTRAINT "cards_password_format_chk" CHECK ("password" is null or "password" ~ '^[0-9]{8}$')
);
--> statement-breakpoint
CREATE TABLE "yugioh_data"."card_sources" (
	"source" text,
	"source_record_id" text,
	"card_id" bigint NOT NULL,
	"source_hash" text NOT NULL,
	"first_seen_batch_id" uuid NOT NULL,
	"last_seen_batch_id" uuid NOT NULL,
	"retired_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "card_sources_pkey" PRIMARY KEY("source","source_record_id")
);
--> statement-breakpoint
CREATE TABLE "yugioh_data"."import_batches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"source" text NOT NULL,
	"source_url" text NOT NULL,
	"archive_hash" text,
	"etag" text,
	"last_modified" text,
	"unknown_fields" text[] DEFAULT '{}'::text[] NOT NULL,
	"source_record_count" integer DEFAULT 0 NOT NULL,
	"added_count" integer DEFAULT 0 NOT NULL,
	"updated_count" integer DEFAULT 0 NOT NULL,
	"skipped_count" integer DEFAULT 0 NOT NULL,
	"failed_count" integer DEFAULT 0 NOT NULL,
	"soft_deleted_count" integer DEFAULT 0 NOT NULL,
	"status" "yugioh_data"."import_batch_status" DEFAULT 'running'::"yugioh_data"."import_batch_status" NOT NULL,
	"error" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "import_batches_source_record_count_nonnegative_chk" CHECK ("source_record_count" >= 0),
	CONSTRAINT "import_batches_added_count_nonnegative_chk" CHECK ("added_count" >= 0),
	CONSTRAINT "import_batches_updated_count_nonnegative_chk" CHECK ("updated_count" >= 0),
	CONSTRAINT "import_batches_skipped_count_nonnegative_chk" CHECK ("skipped_count" >= 0),
	CONSTRAINT "import_batches_failed_count_nonnegative_chk" CHECK ("failed_count" >= 0),
	CONSTRAINT "import_batches_soft_deleted_count_nonnegative_chk" CHECK ("soft_deleted_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE "yugioh_data"."import_failures" (
	"batch_id" uuid,
	"source_record_id" text,
	"stage" text NOT NULL,
	"code" text NOT NULL,
	"message" text NOT NULL,
	"payload" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "import_failures_pkey" PRIMARY KEY("batch_id","source_record_id")
);
--> statement-breakpoint
CREATE TABLE "yugioh_data"."import_states" (
	"source" text PRIMARY KEY,
	"source_url" text NOT NULL,
	"last_successful_batch_id" uuid,
	"archive_hash" text,
	"etag" text,
	"last_modified" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "yugioh_data"."publish_baselines" (
	"publish_target_id" text PRIMARY KEY,
	"environment" text NOT NULL,
	"target_fingerprint" text NOT NULL,
	"batch_id" uuid NOT NULL,
	"manifest_hash" text NOT NULL,
	"total_row_count" integer NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "publish_baselines_total_row_count_nonnegative_chk" CHECK ("total_row_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE "yugioh_data"."publish_batches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"publish_target_id" text NOT NULL,
	"environment" text NOT NULL,
	"target_fingerprint" text NOT NULL,
	"manifest_hash" text NOT NULL,
	"previous_manifest_hash" text,
	"total_row_count" integer DEFAULT 0 NOT NULL,
	"changed_row_count" integer DEFAULT 0 NOT NULL,
	"inserted_row_count" integer DEFAULT 0 NOT NULL,
	"updated_row_count" integer DEFAULT 0 NOT NULL,
	"unchanged_row_count" integer DEFAULT 0 NOT NULL,
	"status" "yugioh_data"."publish_batch_status" DEFAULT 'planning'::"yugioh_data"."publish_batch_status" NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	CONSTRAINT "publish_batches_total_row_count_nonnegative_chk" CHECK ("total_row_count" >= 0),
	CONSTRAINT "publish_batches_changed_row_count_nonnegative_chk" CHECK ("changed_row_count" >= 0),
	CONSTRAINT "publish_batches_inserted_row_count_nonnegative_chk" CHECK ("inserted_row_count" >= 0),
	CONSTRAINT "publish_batches_updated_row_count_nonnegative_chk" CHECK ("updated_row_count" >= 0),
	CONSTRAINT "publish_batches_unchanged_row_count_nonnegative_chk" CHECK ("unchanged_row_count" >= 0)
);
--> statement-breakpoint
CREATE TABLE "yugioh_data"."publish_batch_rows" (
	"batch_id" uuid,
	"card_id" bigint,
	"row_hash" text NOT NULL,
	"previous_row_hash" text,
	"action" "yugioh_data"."publish_batch_row_action" NOT NULL,
	"status" "yugioh_data"."publish_batch_row_status" DEFAULT 'pending'::"yugioh_data"."publish_batch_row_status" NOT NULL,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"applied_at" timestamp with time zone,
	CONSTRAINT "publish_batch_rows_pkey" PRIMARY KEY("batch_id","card_id")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "cards_cid_uidx" ON "yugioh"."cards" ("cid");--> statement-breakpoint
CREATE UNIQUE INDEX "cards_password_uidx" ON "yugioh"."cards" ("password");--> statement-breakpoint
CREATE INDEX "cards_deleted_at_idx" ON "yugioh"."cards" ("deleted_at");--> statement-breakpoint
CREATE UNIQUE INDEX "card_sources_source_card_id_uidx" ON "yugioh_data"."card_sources" ("source","card_id");--> statement-breakpoint
CREATE INDEX "card_sources_card_id_idx" ON "yugioh_data"."card_sources" ("card_id");--> statement-breakpoint
CREATE INDEX "card_sources_last_seen_batch_id_idx" ON "yugioh_data"."card_sources" ("last_seen_batch_id");--> statement-breakpoint
CREATE INDEX "card_sources_retired_at_idx" ON "yugioh_data"."card_sources" ("retired_at");--> statement-breakpoint
CREATE INDEX "import_batches_source_started_at_idx" ON "yugioh_data"."import_batches" ("source","started_at");--> statement-breakpoint
CREATE INDEX "import_batches_status_started_at_idx" ON "yugioh_data"."import_batches" ("status","started_at");--> statement-breakpoint
CREATE INDEX "import_batches_archive_hash_idx" ON "yugioh_data"."import_batches" ("archive_hash");--> statement-breakpoint
CREATE INDEX "import_failures_batch_id_idx" ON "yugioh_data"."import_failures" ("batch_id");--> statement-breakpoint
CREATE INDEX "publish_baselines_batch_id_idx" ON "yugioh_data"."publish_baselines" ("batch_id");--> statement-breakpoint
CREATE INDEX "publish_batches_target_status_idx" ON "yugioh_data"."publish_batches" ("publish_target_id","status");--> statement-breakpoint
CREATE INDEX "publish_batches_created_at_idx" ON "yugioh_data"."publish_batches" ("created_at");--> statement-breakpoint
CREATE INDEX "publish_batches_manifest_hash_idx" ON "yugioh_data"."publish_batches" ("manifest_hash");--> statement-breakpoint
CREATE INDEX "publish_batch_rows_batch_status_idx" ON "yugioh_data"."publish_batch_rows" ("batch_id","status");--> statement-breakpoint
CREATE INDEX "publish_batch_rows_batch_action_idx" ON "yugioh_data"."publish_batch_rows" ("batch_id","action");--> statement-breakpoint
ALTER TABLE "yugioh_data"."card_sources" ADD CONSTRAINT "card_sources_card_id_cards_id_fkey" FOREIGN KEY ("card_id") REFERENCES "yugioh"."cards"("id");--> statement-breakpoint
ALTER TABLE "yugioh_data"."card_sources" ADD CONSTRAINT "card_sources_first_seen_batch_id_import_batches_id_fkey" FOREIGN KEY ("first_seen_batch_id") REFERENCES "yugioh_data"."import_batches"("id");--> statement-breakpoint
ALTER TABLE "yugioh_data"."card_sources" ADD CONSTRAINT "card_sources_last_seen_batch_id_import_batches_id_fkey" FOREIGN KEY ("last_seen_batch_id") REFERENCES "yugioh_data"."import_batches"("id");--> statement-breakpoint
ALTER TABLE "yugioh_data"."import_failures" ADD CONSTRAINT "import_failures_batch_id_import_batches_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "yugioh_data"."import_batches"("id");--> statement-breakpoint
ALTER TABLE "yugioh_data"."import_states" ADD CONSTRAINT "import_states_last_successful_batch_id_import_batches_id_fkey" FOREIGN KEY ("last_successful_batch_id") REFERENCES "yugioh_data"."import_batches"("id");--> statement-breakpoint
ALTER TABLE "yugioh_data"."publish_baselines" ADD CONSTRAINT "publish_baselines_batch_id_publish_batches_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "yugioh_data"."publish_batches"("id");--> statement-breakpoint
ALTER TABLE "yugioh_data"."publish_batch_rows" ADD CONSTRAINT "publish_batch_rows_batch_id_publish_batches_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "yugioh_data"."publish_batches"("id");