CREATE SCHEMA "yugioh_data";
--> statement-breakpoint
CREATE SCHEMA "yugioh";
--> statement-breakpoint
CREATE TABLE "yugioh"."cards" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "yugioh"."yugioh_cards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"cid" bigint,
	"password" varchar(8),
	"cn_name" text,
	"sc_name" text,
	"md_name" text,
	"nwbbs_name" text,
	"cnocg_name" text,
	"jp_ruby" text,
	"jp_name" text,
	"en_name" text,
	"md_en_name" text,
	"wiki_en_name" text,
	"set_ext" text,
	"types_text" text,
	"pendulum_description" text,
	"description" text,
	"ot" integer,
	"setcode" bigint,
	"type" bigint,
	"attack" integer,
	"defense" integer,
	"level" integer,
	"race" bigint,
	"attribute" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "cards_cid_positive_chk" CHECK ("cid" is null or "cid" > 0),
	CONSTRAINT "cards_password_format_chk" CHECK ("password" is null or "password" ~ '^[0-9]{8}$')
);
--> statement-breakpoint
CREATE TABLE "yugioh_data"."publish_ledgers" (
	"publish_target_id" text PRIMARY KEY,
	"environment" text NOT NULL,
	"target_fingerprint" text NOT NULL,
	"batch_id" uuid NOT NULL,
	"manifest_hash" text NOT NULL,
	"total_row_count" integer NOT NULL,
	"changed_row_count" integer DEFAULT 0 NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "publish_ledgers_total_row_count_nonnegative_chk" CHECK ("total_row_count" >= 0),
	CONSTRAINT "publish_ledgers_changed_row_count_nonnegative_chk" CHECK ("changed_row_count" >= 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "cards_cid_uidx" ON "yugioh"."cards" ("cid");--> statement-breakpoint
CREATE UNIQUE INDEX "cards_password_uidx" ON "yugioh"."cards" ("password");--> statement-breakpoint
CREATE INDEX "cards_deleted_at_idx" ON "yugioh"."cards" ("deleted_at");--> statement-breakpoint
CREATE INDEX "publish_ledgers_environment_idx" ON "yugioh_data"."publish_ledgers" ("environment");--> statement-breakpoint
CREATE INDEX "publish_ledgers_published_at_idx" ON "yugioh_data"."publish_ledgers" ("published_at");