/* eslint-disable camelcase */
import { Document, Schema } from 'mongoose';

import conn from './db';

import { CardComponent, Colors, Game, Legalities, URI, UUID } from '../scryfall/interface';

export interface IScryfallPart {
    id: string,
    object: 'related_card',
    component: CardComponent,
    name: string,
    type_line: string,
    uri: URI,
}

export interface IScryfallCardFace {
    artist?: string,
    color_indicator?: Colors,
    colors?: Colors,
    flavor_text?: string,
    illustration_id?: UUID,
    image_uris?: Record<string, URI>,
    loyalty?: string,
    mana_cost: string,
    name: string,
    object: 'card_face',
    oracle_text?: string,
    power?: string,
    printed_name?: string,
    printed_text?: string,
    printed_type_line?: string,
    toughness?: string,
    type_line: string,
    watermark?: string,
}

export interface IScryfallCardData {
    // Core Card Fields
    arena_id?: number,
    card_id: UUID,
    lang: string,
    mtgo_id?: number,
    mtgo_foil_id?: number,
    multiverse_ids?: number[],
    tcgplayer_id?: number,
    cardmarket_id?: number,
    object: 'card',
    oracle_id: UUID,
    prints_search_uri: URI,
    ruling_uri: URI,
    scryfall_uri: URI,
    uri: URI,

    // Gameplay Fields
    all_parts?: IScryfallPart[],
    card_faces?: IScryfallCardFace[],
    cmc: number,
    color_identity: Colors,
    color_indicator?: Colors,
    colors?: Colors,
    edhrec_rank?: number,
    foil: boolean,
    hand_modifier?: string,
    keywords: string[],
    layout: string,
    legalities: Legalities,
    life_modifier?: string,
    loyalty?: string,
    mana_cost?: string,
    name: string,
    nonfoil: boolean,
    oracle_text?: string,
    oversized: boolean,
    power?: string,
    produced_mana?: Colors,
    reserved: boolean,
    toughness?: string,
    type_line: string,

    // Print Fields
    artist?: string,
    booster: boolean,
    border_color: string,
    card_back_id: UUID,
    collector_number: string,
    content_warning?: boolean,
    digital: boolean,
    flavor_name?: string,
    flavor_text?: string,
    frame_effects: string[],
    frame: string,
    full_art: boolean,
    games: Game[],
    highres_image: boolean,
    illustration_id?: UUID,
    image_uris?: Record<string, URI>,
    prices: Record<string, string>,
    printed_name?: string,
    printed_text?: string,
    printed_type_line?: string,
    promo: boolean,
    promo_types?: string[],
    purchase_uris: Record<string, URI>,
    rarity: string,
    related_uris: Record<string, URI>,
    released_at: string,
    reprint: boolean,
    scryfall_set_uri: URI,
    set_name: string,
    set_search_uri: URI,
    set_type: string,
    set_uri: URI,
    set_id: string, // set in scryfall document
    story_spotlight: boolean,
    textless: boolean,
    variation: boolean,
    variation_of?: string,
    watermark?: string,

    preview?: {
        previewed_at: string,
        source_uri: URI,
        source: string,
    },
}

export const ScryfallCardSchema = new Schema({
    // Core Card Fields
    arena_id:          Number,
    card_id:           String,
    lang:              String,
    mtgo_id:           Number,
    mtgo_foil_id:      Number,
    multiverse_ids:    [Number],
    tcgplayer_id:      Number,
    cardmarket_id:     Number,
    object:            String,
    oracle_id:         String,
    prints_search_uri: String,
    ruling_uri:        String,
    scryfall_uri:      String,
    uri:               String,

    // Gameplay Fields
    all_parts: [
        {
            id:        String,
            object:    String,
            component: String,
            name:      String,
            type_line: String,
            uri:       String,
        },
    ],
    card_faces: [
        {
            artist:            String,
            color_indicator:   [String],
            colors:            [String],
            flavor_text:       String,
            illustration_id:   String,
            image_uris:        {},
            loyalty:           String,
            mana_cost:         String,
            name:              String,
            object:            String,
            oracle_text:       String,
            power:             String,
            printed_name:      String,
            printed_text:      String,
            printed_type_line: String,
            toughness:         String,
            type_line:         String,
            watermark:         String,
        },
    ],
    cmc:             Number,
    color_identity:  [String],
    color_indicator: [String],
    colors:          [String],
    edhrec_rank:     Number,
    foil:            Boolean,
    hand_modifier:   String,
    keywords:        [String],
    layout:          String,
    legalities:      {},
    life_modifier:   String,
    loyalty:         String,
    mana_cost:       String,
    name:            String,
    nonfoil:         Boolean,
    oracle_text:     String,
    oversized:       Boolean,
    power:           String,
    produced_mana:   [String],
    reserved:        Boolean,
    toughness:       String,
    type_line:       String,

    // Print Fields
    artist:            String,
    booster:           Boolean,
    border_color:      String,
    card_back_id:      String,
    collector_number:  String,
    content_warning:   Boolean,
    digital:           Boolean,
    flavor_name:       String,
    flavor_text:       String,
    frame_effects:     [String],
    frame:             String,
    full_art:          Boolean,
    games:             [String],
    highres_image:     Boolean,
    illustration_id:   String,
    image_uris:        {},
    prices:            {},
    printed_name:      String,
    printed_text:      String,
    printed_type_line: String,
    promo:             Boolean,
    promo_types:       [String],
    purchase_uris:     {},
    rarity:            String,
    related_uris:      {},
    released_at:       String,
    reprint:           Boolean,
    scryfall_set_uri:  String,
    set_name:          String,
    set_search_uri:    String,
    set_type:          String,
    set_uri:           String,
    set_id:            String,
    story_spotlight:   Boolean,
    textless:          Boolean,
    variation:         Boolean,
    variation_of:      String,
    watermark:         String,

    preview: {
        previewed_at: String,
        source_uri:   String,
        source:       String,
    },
});

const ScryfallCard = conn.model<IScryfallCardData & Document>('scryfall_card', ScryfallCardSchema);

export default ScryfallCard;
