/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoginWindow: typeof import('./src/components/LoginWindow.vue')['default']
    MainWindow: typeof import('./src/components/MainWindow.vue')['default']
    UAlert: typeof import('./../../node_modules/.bun/@nuxt+ui@4.7.0+8642dc759bb14a69/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/.bun/@nuxt+ui@4.7.0+8642dc759bb14a69/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./../../node_modules/.bun/@nuxt+ui@4.7.0+8642dc759bb14a69/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.bun/@nuxt+ui@4.7.0+8642dc759bb14a69/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UFormField: typeof import('./../../node_modules/.bun/@nuxt+ui@4.7.0+8642dc759bb14a69/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../node_modules/.bun/@nuxt+ui@4.7.0+8642dc759bb14a69/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.bun/@nuxt+ui@4.7.0+8642dc759bb14a69/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  }
}
