/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoginWindow: typeof import('./src/components/LoginWindow.vue')['default']
    MainWindow: typeof import('./src/components/MainWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YamlEditor: typeof import('./src/components/YamlEditor.vue')['default']
  }
}
