//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone", table_name = "entity_relations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub source_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub source_revision_hash: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub relation: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub target_id: String,
    pub version: Vec<i32>,
    pub is_latest: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
