//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::ChangeType;
use super::sea_orm_active_enums::Locale;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone", table_name = "entity_localizations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub card_id: String,
    pub version: Vec<i32>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub lang: Locale,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub revision_hash: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub localization_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub render_hash: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub render_model: Option<Json>,
    pub is_latest: bool,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    #[sea_orm(column_type = "Text")]
    pub rich_text: String,
    #[sea_orm(column_type = "Text")]
    pub display_text: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub target_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub text_in_play: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub how_to_earn: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub how_to_earn_golden: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub flavor_text: Option<String>,
    pub loc_change_type: ChangeType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
