//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::ChangeType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone", table_name = "entities")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub card_id: String,
    pub version: Vec<i32>,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub revision_hash: String,
    pub dbf_id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub legacy_payload: Json,
    #[sea_orm(column_type = "Text")]
    pub set: String,
    pub class: Vec<String>,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub cost: i32,
    pub attack: Option<i32>,
    pub health: Option<i32>,
    pub durability: Option<i32>,
    pub armor: Option<i32>,
    pub rune: Option<Vec<String>>,
    pub race: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub spell_school: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub quest_type: Option<String>,
    pub quest_progress: Option<i32>,
    pub quest_part: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hero_power: Option<String>,
    pub tech_level: Option<i32>,
    pub in_bobs_tavern: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub triple_card: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub race_bucket: Option<String>,
    pub armor_bucket: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub buddy: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub banned_race: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mercenary_role: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub mercenary_faction: Option<String>,
    pub colddown: Option<i32>,
    pub collectible: bool,
    pub elite: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub rarity: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub artist: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub override_watermark: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub faction: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub mechanics: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub referenced_tags: Json,
    #[sea_orm(column_type = "Text")]
    pub text_builder_type: String,
    pub change_type: ChangeType,
    pub is_latest: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
