//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::GameChangeType;
use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone", table_name = "format_changes")]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub source: String,
    #[sea_orm(column_type = "Text")]
    pub date: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub effective_date: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub version: i32,
    pub last_version: Option<i32>,
    pub link: Vec<String>,
    pub r#type: GameChangeType,
    #[sea_orm(column_type = "Text", nullable)]
    pub format: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub card_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub set_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub rule_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub group: Option<String>,
    pub status: Option<Status>,
    pub score: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub adjustment: Option<Json>,
    pub related_cards: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
