//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone", table_name = "formats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub format_id: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub localization: Json,
    pub sets: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary")]
    pub banlist: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub birthday: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub deathdate: Option<String>,
    pub tags: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
