//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone", table_name = "patches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub build_number: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub short_name: String,
    #[sea_orm(column_type = "Text")]
    pub hash: String,
    pub is_latest: bool,
    pub is_updated: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
