//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "change_type")]
pub enum ChangeType {
    #[sea_orm(string_value = "unknown")]
    Unknown,
    #[sea_orm(string_value = "major")]
    Major,
    #[sea_orm(string_value = "minor")]
    Minor,
    #[sea_orm(string_value = "non-functional")]
    NonFunctional,
    #[sea_orm(string_value = "wording")]
    Wording,
    #[sea_orm(string_value = "bugged")]
    Bugged,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "game_change_type")]
pub enum GameChangeType {
    #[sea_orm(string_value = "card_change")]
    CardChange,
    #[sea_orm(string_value = "card_change")]
    CardChange,
    #[sea_orm(string_value = "set_change")]
    SetChange,
    #[sea_orm(string_value = "set_change")]
    SetChange,
    #[sea_orm(string_value = "rule_change")]
    RuleChange,
    #[sea_orm(string_value = "rule_change")]
    RuleChange,
    #[sea_orm(string_value = "format_death")]
    FormatDeath,
    #[sea_orm(string_value = "format_death")]
    FormatDeath,
    #[sea_orm(string_value = "card_adjustment")]
    CardAdjustment,
    #[sea_orm(string_value = "card_adjustment")]
    CardAdjustment,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "locale")]
pub enum Locale {
    #[sea_orm(string_value = "en")]
    En,
    #[sea_orm(string_value = "en")]
    En,
    #[sea_orm(string_value = "de")]
    De,
    #[sea_orm(string_value = "zhs")]
    Zhs,
    #[sea_orm(string_value = "es")]
    Es,
    #[sea_orm(string_value = "zht")]
    Zht,
    #[sea_orm(string_value = "de")]
    De,
    #[sea_orm(string_value = "fr")]
    Fr,
    #[sea_orm(string_value = "fr")]
    Fr,
    #[sea_orm(string_value = "it")]
    It,
    #[sea_orm(string_value = "it")]
    It,
    #[sea_orm(string_value = "ja")]
    Ja,
    #[sea_orm(string_value = "ja")]
    Ja,
    #[sea_orm(string_value = "ko")]
    Ko,
    #[sea_orm(string_value = "ko")]
    Ko,
    #[sea_orm(string_value = "mx")]
    Mx,
    #[sea_orm(string_value = "pl")]
    Pl,
    #[sea_orm(string_value = "pt")]
    Pt,
    #[sea_orm(string_value = "pt")]
    Pt,
    #[sea_orm(string_value = "ru")]
    Ru,
    #[sea_orm(string_value = "es")]
    Es,
    #[sea_orm(string_value = "ru")]
    Ru,
    #[sea_orm(string_value = "ph")]
    Ph,
    #[sea_orm(string_value = "th")]
    Th,
    #[sea_orm(string_value = "he")]
    He,
    #[sea_orm(string_value = "zhs")]
    Zhs,
    #[sea_orm(string_value = "ar")]
    Ar,
    #[sea_orm(string_value = "zht")]
    Zht,
    #[sea_orm(string_value = "sa")]
    Sa,
    #[sea_orm(string_value = "grc")]
    Grc,
    #[sea_orm(string_value = "la")]
    La,
    #[sea_orm(string_value = "qya")]
    Qya,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "banned_in_card_pool")]
    BannedInCardPool,
    #[sea_orm(string_value = "banned_in_deck")]
    BannedInDeck,
    #[sea_orm(string_value = "banned")]
    Banned,
    #[sea_orm(string_value = "derived")]
    Derived,
    #[sea_orm(string_value = "legal")]
    Legal,
    #[sea_orm(string_value = "minor")]
    Minor,
    #[sea_orm(string_value = "unavailable")]
    Unavailable,
    #[sea_orm(string_value = "score")]
    Score,
    #[sea_orm(string_value = "buff")]
    Buff,
    #[sea_orm(string_value = "nerf")]
    Nerf,
    #[sea_orm(string_value = "adjust")]
    Adjust,
}
