//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone", table_name = "sets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub set_id: String,
    pub dbf_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub slug: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub release_date: String,
    pub card_count_full: Option<i32>,
    pub card_count: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub group: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
