//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone", table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub enum_id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    pub slug_aliases: Vec<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub raw_type: Option<String>,
    pub raw_names: Vec<String>,
    #[sea_orm(column_type = "Text")]
    pub value_kind: String,
    #[sea_orm(column_type = "Text")]
    pub normalize_kind: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub normalize_config: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_target_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_target_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub project_kind: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub project_config: Json,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub first_seen_source_tag: Option<i32>,
    pub last_seen_source_tag: Option<i32>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
