DROP VIEW "hearthstone"."card_entity_view";--> statement-breakpoint
DROP VIEW "hearthstone"."entity_view";--> statement-breakpoint
DROP TABLE "hearthstone_data"."publish_row_change_logs";--> statement-breakpoint
ALTER TABLE "hearthstone_data"."publish_baselines" DROP CONSTRAINT "publish_baselines_source_tag_range_chk";--> statement-breakpoint
ALTER TABLE "hearthstone_data"."publish_baselines" DROP CONSTRAINT "publish_baselines_source_tag_min_positive_chk";--> statement-breakpoint
ALTER TABLE "hearthstone_data"."publish_batches" DROP CONSTRAINT "publish_batches_source_tag_range_chk";--> statement-breakpoint
ALTER TABLE "hearthstone_data"."publish_batches" DROP CONSTRAINT "publish_batches_source_tag_min_positive_chk";--> statement-breakpoint
ALTER TABLE "hearthstone"."cards" ADD COLUMN "deleted_at" timestamp;--> statement-breakpoint
ALTER TABLE "hearthstone"."entity_relations" ADD COLUMN "deleted_at" timestamp;--> statement-breakpoint
ALTER TABLE "hearthstone"."entities" ADD COLUMN "deleted_at" timestamp;--> statement-breakpoint
ALTER TABLE "hearthstone"."entity_localizations" ADD COLUMN "deleted_at" timestamp;--> statement-breakpoint
ALTER TABLE "hearthstone_data"."publish_baselines" DROP COLUMN "source_tag_min";--> statement-breakpoint
ALTER TABLE "hearthstone_data"."publish_baselines" DROP COLUMN "source_tag_max";--> statement-breakpoint
ALTER TABLE "hearthstone_data"."publish_batches" DROP COLUMN "source_tag_min";--> statement-breakpoint
ALTER TABLE "hearthstone_data"."publish_batches" DROP COLUMN "source_tag_max";--> statement-breakpoint
DROP INDEX "entity_relations_source_idx";--> statement-breakpoint
CREATE INDEX "entity_relations_source_idx" ON "hearthstone"."entity_relations" ("source_id") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entity_relations_target_idx";--> statement-breakpoint
CREATE INDEX "entity_relations_target_idx" ON "hearthstone"."entity_relations" ("target_id") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entity_relations_source_relation_idx";--> statement-breakpoint
CREATE INDEX "entity_relations_source_relation_idx" ON "hearthstone"."entity_relations" ("source_id","relation") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entity_relations_target_relation_idx";--> statement-breakpoint
CREATE INDEX "entity_relations_target_relation_idx" ON "hearthstone"."entity_relations" ("target_id","relation") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entity_relations_latest_idx";--> statement-breakpoint
CREATE INDEX "entity_relations_latest_idx" ON "hearthstone"."entity_relations" ("is_latest") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entity_relations_version_gin_idx";--> statement-breakpoint
CREATE INDEX "entity_relations_version_gin_idx" ON "hearthstone"."entity_relations" USING gin ("version") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entities_latest_idx";--> statement-breakpoint
CREATE INDEX "entities_latest_idx" ON "hearthstone"."entities" ("is_latest") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entities_version_gin_idx";--> statement-breakpoint
CREATE INDEX "entities_version_gin_idx" ON "hearthstone"."entities" USING gin ("version") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entity_localizations_card_lang_idx";--> statement-breakpoint
CREATE INDEX "entity_localizations_card_lang_idx" ON "hearthstone"."entity_localizations" ("card_id","lang") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entity_localizations_latest_idx";--> statement-breakpoint
CREATE INDEX "entity_localizations_latest_idx" ON "hearthstone"."entity_localizations" ("is_latest") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entity_localizations_version_gin_idx";--> statement-breakpoint
CREATE INDEX "entity_localizations_version_gin_idx" ON "hearthstone"."entity_localizations" USING gin ("version") WHERE "deleted_at" is null;--> statement-breakpoint
DROP INDEX "entity_localizations_render_hash_idx";--> statement-breakpoint
CREATE INDEX "entity_localizations_render_hash_idx" ON "hearthstone"."entity_localizations" ("render_hash") WHERE ("render_hash" is not null and "deleted_at" is null);--> statement-breakpoint
CREATE INDEX "cards_deleted_at_idx" ON "hearthstone"."cards" ("deleted_at") WHERE "deleted_at" is not null;--> statement-breakpoint
CREATE INDEX "entity_relations_deleted_at_idx" ON "hearthstone"."entity_relations" ("deleted_at") WHERE "deleted_at" is not null;--> statement-breakpoint
CREATE INDEX "entities_deleted_at_idx" ON "hearthstone"."entities" ("deleted_at") WHERE "deleted_at" is not null;--> statement-breakpoint
CREATE INDEX "entity_localizations_deleted_at_idx" ON "hearthstone"."entity_localizations" ("deleted_at") WHERE "deleted_at" is not null;--> statement-breakpoint
CREATE VIEW "hearthstone"."active_cards" AS (select "card_id", "legalities", "created_at", "updated_at", "deleted_at" from "hearthstone"."cards" where "hearthstone"."cards"."deleted_at" is null);--> statement-breakpoint
CREATE VIEW "hearthstone"."active_entity_relations" AS (select "source_id", "source_revision_hash", "relation", "target_id", "version", "is_latest", "created_at", "updated_at", "deleted_at" from "hearthstone"."entity_relations" where "hearthstone"."entity_relations"."deleted_at" is null);--> statement-breakpoint
CREATE VIEW "hearthstone"."active_entities" AS (select "card_id", "version", "revision_hash", "dbf_id", "legacy_payload", "set", "class", "type", "cost", "attack", "health", "durability", "armor", "rune", "race", "spell_school", "quest_type", "quest_progress", "quest_part", "hero_power", "tech_level", "in_bobs_tavern", "triple_card", "race_bucket", "armor_bucket", "buddy", "banned_race", "mercenary_role", "mercenary_faction", "colddown", "collectible", "elite", "rarity", "artist", "override_watermark", "faction", "mechanics", "referenced_tags", "text_builder_type", "change_type", "is_latest", "created_at", "updated_at", "deleted_at" from "hearthstone"."entities" where "hearthstone"."entities"."deleted_at" is null);--> statement-breakpoint
CREATE VIEW "hearthstone"."active_entity_localizations" AS (select "card_id", "version", "lang", "revision_hash", "localization_hash", "render_hash", "render_model", "is_latest", "name", "text", "rich_text", "display_text", "target_text", "text_in_play", "how_to_earn", "how_to_earn_golden", "flavor_text", "loc_change_type", "created_at", "updated_at", "deleted_at" from "hearthstone"."entity_localizations" where "hearthstone"."entity_localizations"."deleted_at" is null);--> statement-breakpoint
CREATE VIEW "hearthstone"."card_entity_view" AS (select "hearthstone"."entities"."card_id", "hearthstone"."entities"."version" & "hearthstone"."entity_localizations"."version" as "version", "hearthstone"."entity_localizations"."lang", "hearthstone"."entities"."revision_hash", "hearthstone"."entity_localizations"."localization_hash", "hearthstone"."entity_localizations"."render_hash", "hearthstone"."entities"."dbf_id", "hearthstone"."entities"."legacy_payload", "hearthstone"."entities"."set", "hearthstone"."entities"."class", "hearthstone"."entities"."type", "hearthstone"."entities"."cost", "hearthstone"."entities"."attack", "hearthstone"."entities"."health", "hearthstone"."entities"."durability", "hearthstone"."entities"."armor", "hearthstone"."entities"."rune", "hearthstone"."entities"."race", "hearthstone"."entities"."spell_school", "hearthstone"."entities"."quest_type", "hearthstone"."entities"."quest_progress", "hearthstone"."entities"."quest_part", "hearthstone"."entities"."hero_power", "hearthstone"."entities"."tech_level", "hearthstone"."entities"."in_bobs_tavern", "hearthstone"."entities"."triple_card", "hearthstone"."entities"."race_bucket", "hearthstone"."entities"."armor_bucket", "hearthstone"."entities"."buddy", "hearthstone"."entities"."banned_race", "hearthstone"."entities"."mercenary_role", "hearthstone"."entities"."mercenary_faction", "hearthstone"."entities"."colddown", "hearthstone"."entities"."collectible", "hearthstone"."entities"."elite", "hearthstone"."entities"."rarity", "hearthstone"."entities"."artist", "hearthstone"."entities"."override_watermark", "hearthstone"."entities"."faction", "hearthstone"."entities"."mechanics", "hearthstone"."entities"."referenced_tags", "hearthstone"."entities"."text_builder_type", "hearthstone"."entities"."change_type", "hearthstone"."entities"."is_latest", "hearthstone"."entity_localizations"."name", "hearthstone"."entity_localizations"."text", "hearthstone"."entity_localizations"."rich_text", "hearthstone"."entity_localizations"."display_text", "hearthstone"."entity_localizations"."target_text", "hearthstone"."entity_localizations"."text_in_play", "hearthstone"."entity_localizations"."how_to_earn", "hearthstone"."entity_localizations"."how_to_earn_golden", "hearthstone"."entity_localizations"."flavor_text", "hearthstone"."entity_localizations"."loc_change_type", "hearthstone"."cards"."legalities" from "hearthstone"."entities" inner join "hearthstone"."entity_localizations" on ("hearthstone"."entities"."card_id" = "hearthstone"."entity_localizations"."card_id" and "hearthstone"."entities"."revision_hash" = "hearthstone"."entity_localizations"."revision_hash" and "hearthstone"."entities"."version" && "hearthstone"."entity_localizations"."version") inner join "hearthstone"."cards" on "hearthstone"."entities"."card_id" = "hearthstone"."cards"."card_id" where "hearthstone"."entities"."deleted_at" is null and "hearthstone"."entity_localizations"."deleted_at" is null);--> statement-breakpoint
CREATE VIEW "hearthstone"."entity_view" AS (select "hearthstone"."entities"."card_id", "hearthstone"."entities"."version" & "hearthstone"."entity_localizations"."version" as "version", "hearthstone"."entity_localizations"."lang", "hearthstone"."entities"."dbf_id", "hearthstone"."entities"."legacy_payload", "hearthstone"."entities"."set", "hearthstone"."entities"."class", "hearthstone"."entities"."type", "hearthstone"."entities"."cost", "hearthstone"."entities"."attack", "hearthstone"."entities"."health", "hearthstone"."entities"."durability", "hearthstone"."entities"."armor", "hearthstone"."entities"."rune", "hearthstone"."entities"."race", "hearthstone"."entities"."spell_school", "hearthstone"."entities"."quest_type", "hearthstone"."entities"."quest_progress", "hearthstone"."entities"."quest_part", "hearthstone"."entities"."hero_power", "hearthstone"."entities"."tech_level", "hearthstone"."entities"."in_bobs_tavern", "hearthstone"."entities"."triple_card", "hearthstone"."entities"."race_bucket", "hearthstone"."entities"."armor_bucket", "hearthstone"."entities"."buddy", "hearthstone"."entities"."banned_race", "hearthstone"."entities"."mercenary_role", "hearthstone"."entities"."mercenary_faction", "hearthstone"."entities"."colddown", "hearthstone"."entities"."collectible", "hearthstone"."entities"."elite", "hearthstone"."entities"."rarity", "hearthstone"."entities"."artist", "hearthstone"."entities"."override_watermark", "hearthstone"."entities"."faction", "hearthstone"."entities"."mechanics", "hearthstone"."entities"."referenced_tags", "hearthstone"."entities"."text_builder_type", "hearthstone"."entities"."change_type", "hearthstone"."entities"."is_latest", "hearthstone"."entities"."deleted_at", "hearthstone"."entity_localizations"."name", "hearthstone"."entity_localizations"."text", "hearthstone"."entity_localizations"."rich_text", "hearthstone"."entity_localizations"."display_text", "hearthstone"."entity_localizations"."target_text", "hearthstone"."entity_localizations"."text_in_play", "hearthstone"."entity_localizations"."how_to_earn", "hearthstone"."entity_localizations"."how_to_earn_golden", "hearthstone"."entity_localizations"."flavor_text", "hearthstone"."entity_localizations"."loc_change_type" from "hearthstone"."entities" inner join "hearthstone"."entity_localizations" on ("hearthstone"."entities"."card_id" = "hearthstone"."entity_localizations"."card_id" and "hearthstone"."entities"."revision_hash" = "hearthstone"."entity_localizations"."revision_hash" and "hearthstone"."entities"."version" && "hearthstone"."entity_localizations"."version") where "hearthstone"."entities"."deleted_at" is null and "hearthstone"."entity_localizations"."deleted_at" is null);