//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::HsdataImportChunkStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "hearthstone_data",
    table_name = "hsdata_import_job_chunks"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub job_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub chunk_index: i32,
    pub entity_count: i32,
    #[sea_orm(column_type = "Text")]
    pub payload_hash: String,
    pub status: HsdataImportChunkStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    pub claimed_at: Option<DateTime>,
    pub completed_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hsdata_import_jobs::Entity",
        from = "Column::JobId",
        to = "super::hsdata_import_jobs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    HsdataImportJobs,
}

impl Related<super::hsdata_import_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HsdataImportJobs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
