//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::HsdataImportCleanupStatus;
use super::sea_orm_active_enums::HsdataImportJobStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone_data", table_name = "hsdata_import_jobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub source_tag: i32,
    #[sea_orm(column_type = "Text")]
    pub source_commit: String,
    #[sea_orm(column_type = "Text")]
    pub source_uri: String,
    pub build: i32,
    #[sea_orm(column_type = "Text")]
    pub source_hash: String,
    #[sea_orm(column_type = "Text")]
    pub manifest_hash: String,
    #[sea_orm(column_type = "Text")]
    pub chunking_version: String,
    #[sea_orm(column_type = "Text")]
    pub payload_format_version: String,
    #[sea_orm(column_type = "Text")]
    pub payload_encoding: String,
    #[sea_orm(column_type = "Text")]
    pub import_engine_version: String,
    pub max_bytes_per_chunk: i32,
    pub max_entities_per_chunk: i32,
    pub dry_run: bool,
    pub force: bool,
    pub total_chunk_count: i32,
    pub total_entity_count: i32,
    pub status: HsdataImportJobStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub error: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub report: Option<Json>,
    pub staging_cleanup_status: HsdataImportCleanupStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub staging_cleanup_error: Option<String>,
    pub cleaned_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub finalized_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hsdata_import_job_chunks::Entity")]
    HsdataImportJobChunks,
    #[sea_orm(has_many = "super::hsdata_import_job_snapshots::Entity")]
    HsdataImportJobSnapshots,
}

impl Related<super::hsdata_import_job_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HsdataImportJobChunks.def()
    }
}

impl Related<super::hsdata_import_job_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HsdataImportJobSnapshots.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
