//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "hearthstone_data",
    table_name = "hsdata_import_job_snapshots"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub job_id: Uuid,
    pub chunk_index: i32,
    #[sea_orm(column_type = "Text")]
    pub card_id: String,
    pub dbf_id: i32,
    pub entity_xml_version: i32,
    #[sea_orm(column_type = "Text")]
    pub snapshot_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub tags: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub extra_payload: Json,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hsdata_import_jobs::Entity",
        from = "Column::JobId",
        to = "super::hsdata_import_jobs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    HsdataImportJobs,
}

impl Related<super::hsdata_import_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HsdataImportJobs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
