//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone_data", table_name = "raw_entity_snapshots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub card_id: String,
    pub dbf_id: i32,
    pub source_tags: Vec<i32>,
    pub entity_xml_version: i32,
    #[sea_orm(column_type = "Text")]
    pub snapshot_hash: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub extra_payload: Json,
    pub is_latest: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::raw_entity_snapshot_tags::Entity")]
    RawEntitySnapshotTags,
}

impl Related<super::raw_entity_snapshot_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RawEntitySnapshotTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
