//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(
    schema_name = "hearthstone_data",
    table_name = "raw_entity_snapshot_tags"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub snapshot_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub enum_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_order: i32,
    #[sea_orm(column_type = "Text")]
    pub raw_name: String,
    #[sea_orm(column_type = "Text")]
    pub raw_type: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub raw_payload: Json,
    #[sea_orm(column_type = "Text")]
    pub value_kind: String,
    pub bool_value: Option<bool>,
    pub int_value: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub string_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub enum_value: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub loc_string_value: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub card_ref_card_id: Option<String>,
    pub card_ref_dbf_id: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub json_value: Option<Json>,
    #[sea_orm(column_type = "Text")]
    pub parse_status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::raw_entity_snapshots::Entity",
        from = "Column::SnapshotId",
        to = "super::raw_entity_snapshots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    RawEntitySnapshots,
    #[sea_orm(
        belongs_to = "super::tags::Entity",
        from = "Column::EnumId",
        to = "super::tags::Column::EnumId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tags,
}

impl Related<super::raw_entity_snapshots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RawEntitySnapshots.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
