//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::HsdataProjectionStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "hearthstone_data", table_name = "source_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_tag: i32,
    #[sea_orm(column_type = "Text")]
    pub source_commit: String,
    pub build: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub source_hash: String,
    #[sea_orm(column_type = "Text")]
    pub source_uri: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub import_engine_version: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub projection_status: HsdataProjectionStatus,
    #[sea_orm(column_type = "Text", nullable)]
    pub projection_error: Option<String>,
    pub imported_at: Option<DateTime>,
    pub projected_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
