CREATE SCHEMA "yugioh_data";
--> statement-breakpoint
CREATE SCHEMA "yugioh";
--> statement-breakpoint
CREATE TABLE "yugioh"."cards" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "yugioh"."yugioh_cards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"cid" bigint,
	"password" varchar(8),
	"cn_name" text,
	"sc_name" text,
	"md_name" text,
	"nwbbs_name" text,
	"cnocg_name" text,
	"jp_ruby" text,
	"jp_name" text,
	"en_name" text,
	"md_en_name" text,
	"wiki_en_name" text,
	"set_ext" text,
	"types_text" text,
	"pendulum_description" text,
	"description" text,
	"ot" integer,
	"setcode" bigint,
	"type" bigint,
	"attack" integer,
	"defense" integer,
	"level" integer,
	"race" bigint,
	"attribute" bigint,
	"primary_image_r2_bucket" text,
	"primary_image_r2_key" text,
	"primary_image_content_type" text,
	"primary_image_byte_size" integer,
	"primary_image_width" integer,
	"primary_image_height" integer,
	"primary_image_sha256" varchar(64),
	"primary_image_deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "cards_cid_positive_chk" CHECK ("cid" is null or "cid" > 0),
	CONSTRAINT "cards_password_format_chk" CHECK ("password" is null or "password" ~ '^[0-9]{8}$'),
	CONSTRAINT "cards_primary_image_sha256_format_chk" CHECK ("primary_image_sha256" is null or "primary_image_sha256" ~ '^[a-f0-9]{64}$'),
	CONSTRAINT "cards_primary_image_byte_size_positive_chk" CHECK ("primary_image_byte_size" is null or "primary_image_byte_size" > 0),
	CONSTRAINT "cards_primary_image_width_positive_chk" CHECK ("primary_image_width" is null or "primary_image_width" > 0),
	CONSTRAINT "cards_primary_image_height_positive_chk" CHECK ("primary_image_height" is null or "primary_image_height" > 0),
	CONSTRAINT "cards_primary_image_fields_complete_chk" CHECK (
    ("primary_image_r2_key" is null
      and "primary_image_r2_bucket" is null
      and "primary_image_content_type" is null
      and "primary_image_byte_size" is null
      and "primary_image_width" is null
      and "primary_image_height" is null
      and "primary_image_sha256" is null)
    or
    ("primary_image_r2_key" is not null
      and "primary_image_r2_bucket" is not null
      and "primary_image_content_type" is not null
      and "primary_image_byte_size" is not null
      and "primary_image_width" is not null
      and "primary_image_height" is not null
      and "primary_image_sha256" is not null)
  )
);
--> statement-breakpoint
CREATE TABLE "yugioh_data"."publish_ledgers" (
	"publish_target_id" text PRIMARY KEY,
	"environment" text NOT NULL,
	"target_fingerprint" text NOT NULL,
	"batch_id" uuid NOT NULL,
	"manifest_hash" text NOT NULL,
	"total_row_count" integer NOT NULL,
	"changed_row_count" integer DEFAULT 0 NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "publish_ledgers_total_row_count_nonnegative_chk" CHECK ("total_row_count" >= 0),
	CONSTRAINT "publish_ledgers_changed_row_count_nonnegative_chk" CHECK ("changed_row_count" >= 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "cards_cid_uidx" ON "yugioh"."cards" ("cid");--> statement-breakpoint
CREATE UNIQUE INDEX "cards_password_uidx" ON "yugioh"."cards" ("password");--> statement-breakpoint
CREATE UNIQUE INDEX "cards_primary_image_r2_key_uidx" ON "yugioh"."cards" ("primary_image_r2_key");--> statement-breakpoint
CREATE INDEX "cards_deleted_at_idx" ON "yugioh"."cards" ("deleted_at");--> statement-breakpoint
CREATE INDEX "cards_primary_image_deleted_at_idx" ON "yugioh"."cards" ("primary_image_deleted_at");--> statement-breakpoint
CREATE INDEX "publish_ledgers_environment_idx" ON "yugioh_data"."publish_ledgers" ("environment");--> statement-breakpoint
CREATE INDEX "publish_ledgers_published_at_idx" ON "yugioh_data"."publish_ledgers" ("published_at");