DROP VIEW "hearthstone_data"."tag_value_view";--> statement-breakpoint
ALTER TABLE "hearthstone_data"."raw_entity_snapshots" RENAME COLUMN "version" TO "source_tags";--> statement-breakpoint
CREATE INDEX "entity_relations_version_gin_idx" ON "hearthstone"."entity_relations" USING gin ("version");--> statement-breakpoint
CREATE INDEX "entities_latest_idx" ON "hearthstone"."entities" ("is_latest");--> statement-breakpoint
CREATE INDEX "entities_version_gin_idx" ON "hearthstone"."entities" USING gin ("version");--> statement-breakpoint
CREATE INDEX "entity_localizations_card_lang_idx" ON "hearthstone"."entity_localizations" ("card_id","lang");--> statement-breakpoint
CREATE INDEX "entity_localizations_latest_idx" ON "hearthstone"."entity_localizations" ("is_latest");--> statement-breakpoint
CREATE INDEX "entity_localizations_version_gin_idx" ON "hearthstone"."entity_localizations" USING gin ("version");--> statement-breakpoint
CREATE INDEX "raw_entity_snapshots_source_tags_gin_idx" ON "hearthstone_data"."raw_entity_snapshots" USING gin ("source_tags");--> statement-breakpoint
ALTER TABLE "hearthstone"."entity_relations" ADD CONSTRAINT "entity_relations_version_nonempty_chk" CHECK (cardinality("version") > 0);--> statement-breakpoint
ALTER TABLE "hearthstone"."entities" ADD CONSTRAINT "entities_version_nonempty_chk" CHECK (cardinality("version") > 0);--> statement-breakpoint
ALTER TABLE "hearthstone"."entity_localizations" ADD CONSTRAINT "entity_localizations_version_nonempty_chk" CHECK (cardinality("version") > 0);--> statement-breakpoint
ALTER TABLE "hearthstone_data"."raw_entity_snapshots" ADD CONSTRAINT "raw_entity_snapshots_source_tags_nonempty_chk" CHECK (cardinality("source_tags") > 0);--> statement-breakpoint
CREATE VIEW "hearthstone_data"."tag_value_view" AS (select "hearthstone_data"."raw_entity_snapshot_tags"."snapshot_id", "hearthstone_data"."raw_entity_snapshots"."card_id", "hearthstone_data"."raw_entity_snapshots"."dbf_id", "hearthstone_data"."raw_entity_snapshots"."source_tags", "hearthstone_data"."raw_entity_snapshot_tags"."enum_id", "hearthstone"."tags"."slug" as "tag_slug", "hearthstone"."tags"."name" as "tag_name", "hearthstone_data"."raw_entity_snapshot_tags"."value_kind", "hearthstone_data"."raw_entity_snapshot_tags"."bool_value", "hearthstone_data"."raw_entity_snapshot_tags"."int_value", "hearthstone_data"."raw_entity_snapshot_tags"."string_value", "hearthstone_data"."raw_entity_snapshot_tags"."enum_value", "hearthstone_data"."raw_entity_snapshot_tags"."loc_string_value", "hearthstone_data"."raw_entity_snapshot_tags"."card_ref_card_id", "hearthstone_data"."raw_entity_snapshot_tags"."card_ref_dbf_id", "hearthstone_data"."raw_entity_snapshot_tags"."json_value" from "hearthstone_data"."raw_entity_snapshot_tags" inner join "hearthstone_data"."raw_entity_snapshots" on "hearthstone_data"."raw_entity_snapshot_tags"."snapshot_id" = "hearthstone_data"."raw_entity_snapshots"."id" inner join "hearthstone"."tags" on "hearthstone_data"."raw_entity_snapshot_tags"."enum_id" = "hearthstone"."tags"."enum_id");