export const localization = {
  gameplayStrings: {
    GALAKROND_ONCE:              'Zum Aufwerten einmal Galakrond <b>ermächtigen</b>.',
    GALAKROND_TWICE:             'Zum Aufwerten zweimal Galakrond <b>ermächtigen</b>.',
    GAMEPLAY_UNKNOWN_CREATED_BY: 'eine andere Karte',
  },
  keywordNames: [
    'Spott',
    'Einfrieren',
    'Ehrenhafter Sieg',
    'Arkanzauberschaden',
    'Feuerzauberschaden',
    'Frostzauberschaden',
    'Naturzauberschaden',
    'Heiligzauberschaden',
    'Schattenzauberschaden',
    'Dämonenzauberschaden',
    'Körperlicher Zauberschaden',
    'Blutedelstein',
    'Windzorn',
    'Todesröcheln',
    'Combo',
    'Überladung: X',
    'Zum Schweigen bringen',
    'Konter',
    'Immun',
    'Automatischer Einsatz',
    'Ersatzteil',
    'Aktualisieren',
    'Rache (X)',
    'Arkanwiderstand',
    'Zauberschaden',
    'Inspiration',
    'Feuerwiderstand',
    'Frostwiderstand',
    'Naturwiderstand',
    'Heiligwiderstand',
    'Schattenwiderstand',
    'Teufelswiderstand',
    'Arkanschwäche',
    'Feuerschwäche',
    'Frostschwäche',
    'Naturschwäche',
    'Entdecken',
    'Heiligschwäche',
    'Schattenschwäche',
    'Teufelsschwäche',
    'Angriff',
    'Zaubercombo',
    'C’Thun, Alter Gott',
    'Todesstoß',
    'Blutung',
    'Kritischer Schaden',
    'Festwurzeln',
    'Allianz',
    'Horde',
    'Erneuern',
    'Elfen',
    'Kolossal +X',
    'Bergen',
    'Wiederbelebung (X)',
    'Zauberkunde',
    'Verbündet',
    'Heilkraft',
    'Durchfluten',
    'Durchflutet',
    'Dienertyp',
    'Einfrieren',
    'Zauberschwäche',
    'Zauberwiderstand',
    'Leiche',
    'Bank',
    'Forscher',
    'Automatischer Angriff',
    'Zum Schweigen bringen',
    'Verstohlenheit',
    'Quest',
    'Ansturm',
    'Finale',
    'Überheilung',
    'Manadurst (X)',
    'Wiederkehr',
    'Jadegolem',
    'Seuchenmords Kreation',
    'Toxisch',
    'Bonuseffekte',
    'Erhaltet Euren Partner',
    'Erhaltet 2 Partner',
    'Flüchtig',
    'Schmieden',
    'Geschmiedet',
    'Gassenhauer-Gang',
    'Titan',
    'Jadelotus',
    'Kabale',
    'Wird beim Ziehen herbeigerufen',
    'Verschlingen',
    'Minimieren',
    'Mini',
    'Schnellzug',
    'Ausgraben',
    'Gottesschild',
    'Weitergeben',
    'Gigantifizierung',
    'Gigantisch',
    'Partner',
    'Passiv',
    'Schurkentourist',
    'Hexenmeistertourist',
    'Todesrittertourist',
    'Quest',
    'Schamanentourist',
    'Dämonenjägertourist',
    'Priestertourist',
    'Jägertourist',
    'Kriegertourist',
    'Druidentourist',
    'Magiertourist',
    'Paladintourist',
    'Erfüllen',
    'Dunkle Gabe',
    'Giftig',
    'Temporär',
    'Raumschiff',
    'Schmuckstück',
    'Boss',
    'Reduziert',
    'Bonus-Schlüsselwörter',
    'Protoss',
    'Zerg',
    'Terraner',
    'Mutieren',
    'Zurückspulen',
    'Verwandt',
    'Yamato-Kanone',
    'Verbesserte Ballistik',
    'Caduceus-Reaktor',
    'Sagenhaft',
    'Sagenhaft+',
    'Elementarbonus',
    'Gasthauszauberbonus',
    'Mobilisieren',
    'Entzweien',
    'Entzweit',
    'Ankündigen',
    'Beute',
    'Lebensentzug',
    'Vorbereiten',
    'Rekrutieren',
    'Zeitkrümmung',
    'Anzahl an Aktualisierungen',
    'Ansturm',
    'Provozieren',
    'Piratenbonus',
    'Futter beim Aktualisieren',
    'Chromadrache',
    'Futter',
    'Vorbereiten',
    'Vorbereitet',
    'Geheimnis',
    'Echo',
    'Eifer',
    'Passiv',
    'Verstohlenheit',
    'Überwältigen',
    'Spielbeginn',
    'Wild',
    'Magnetisch',
    'Wutanfall',
    'Lakai',
    'Beim Ziehen gewirkt',
    'Flubbidinius Flurp',
    'Schrein',
    'Zwillingszauber',
    'Super-Windzorn',
    'Wiederkehr',
    'Ermächtigen',
    'Kampfschrei',
    'Ermächtigen: Priester',
    'Ermächtigen: Schurke',
    'Ermächtigen: Schamane',
    'Ermächtigen: Hexenmeister',
    'Ermächtigen: Krieger',
    'Erschöpfung',
    'Außenseiter',
    'Zauberschub',
    'Nebenquest',
    'Eingefroren',
    'Verderben',
    'Inaktiv',
    'Werkzeug',
    'Questreihe',
    'Handelbar',
    'Verderbt',
    'Raserei',
  ],
  heraldNames: {
    GAMEPLAY_HERALD_WARRIOR:     'Ragnaros',
    GAMEPLAY_HERALD_DEMONHUNTER: 'Azshara',
    GAMEPLAY_HERALD_SHAMAN:      'Al’Akir',
    GAMEPLAY_HERALD_ROGUE:       'Sinestra',
    GAMEPLAY_HERALD_DEATHKNIGHT: 'Onyxia',
    GAMEPLAY_HERALD_WARLOCK:     'Cho’gall',
    GAMEPLAY_HERALD_DEFAULT:     'Euren kolossalen Diener',
  },
  gameplayBuilderStrings: {
    GAMEPLAY_DIAMOND_SPELLSTONE_1:     '<i>(Zum Aufwerten 4_Zauber wirken.)</i>',
    GAMEPLAY_PEARL_SPELLSTONE_1:       '<i>(Zum Aufwerten 3_Leben wiederherstellen.)</i>',
    GAMEPLAY_SAPPHIRE_SPELLSTONE_1:    '<i>(Zum Aufwerten 3_Manakristalle <b>überladen</b>.)</i>',
    GAMEPLAY_JASPER_SPELLSTONE_1:      '<i>(Zum Aufwerten 3_Rüstung erhalten.)</i>',
    GAMEPLAY_AMETHYST_SPELLSTONE_1:    '<i>(Zum Aufwerten Schaden durch eigene Karten erleiden.)</i>',
    GAMEPLAY_RUBY_SPELLSTONE_1:        '<i>(Zum Aufwerten 2_Elementare ausspielen.)</i>',
    GAMEPLAY_ONYX_SPELLSTONE_1:        '<i>(Zum Aufwerten 3 <b>Todesröcheln</b>-Karten ausspielen.)</i>',
    GAMEPLAY_LOOT_526d_DARKNESS_1:     'Erwacht, wenn Euer Gegner 3 Kerzen zieht!',
    GAMEPLAY_TOT_109t_STASIS_DRAGON_1: 'Erwacht nach zwei Zügen mit <b>Eifer</b>.',
    GAMEPLAY_TRLA_TROLL_SHRINE_1:      'Wird in 3 Zügen\\nwiederbelebt.',
  },
  raceNames: {
    normal: {
      1:   'Blutelf',
      2:   'Draenei',
      3:   'Zwerg',
      4:   'Gnom',
      5:   'Goblin',
      6:   'Mensch',
      7:   'Nachtelf',
      8:   'Orc',
      9:   'Tauren',
      10:  'Troll',
      11:  'Untot',
      12:  'Worgen',
      14:  'Murloc',
      15:  'Dämon',
      16:  'Geißel',
      17:  'Mech',
      18:  'Elementar',
      19:  'Oger',
      20:  'Wildtier',
      21:  'Totem',
      22:  'Neruber',
      23:  'Pirat',
      24:  'Drache',
      26:  'Alle',
      38:  'Ei',
      43:  'Stacheleber',
      80:  'Zentaur',
      81:  'Furbolg',
      83:  'Hochelf',
      84:  'Treant',
      85:  'Eulkin',
      88:  'Halborc',
      89:  'Schloss',
      92:  'Naga',
      93:  'Alter Gott',
      94:  'Pandaren',
      95:  'Gronn',
      96:  'Erhabener',
      97:  'Gnoll',
      98:  'Golem',
      99:  'Harpyie',
      100: 'Vulpera',
    },
    battlegrounds: {
      1:  'Blutelfen',
      2:  'Draenei',
      3:  'Zwerge',
      4:  'Gnome',
      5:  'Goblins',
      6:  'Menschen',
      7:  'Nachtelfen',
      8:  'Orcs',
      9:  'Tauren',
      10: 'Trolle',
      11: 'Untote',
      12: 'Worgen',
      14: 'Murlocs',
      15: 'Dämonen',
      16: 'Geißel',
      17: 'Mechs',
      18: 'Elementare',
      19: 'Oger',
      20: 'Wildtiere',
      21: 'Totems',
      22: 'Neruber',
      23: 'Piraten',
      24: 'Drachen',
      26: 'Mutationen',
      38: 'Eier',
      43: 'Stacheleber',
      92: 'Naga',
    },
  },
  classNames: {
    1:  'Todesritter',
    2:  'Druide',
    3:  'Jäger',
    4:  'Magier',
    5:  'Paladin',
    6:  'Priester',
    7:  'Schurke',
    8:  'Schamane',
    9:  'Hexenmeister',
    10: 'Krieger',
    12: 'Neutral',
    14: 'Dämonenjäger',
  },
  zilliaxCombinedModuleTexts: {
    ZILLIAX_DELUXE_COMBINED_MODULE_1_2: '<b>Flüchtig</b>, <b>Giftig</b>, <b>Gottesschild</b>, <b>Spott</b>, <b>Lebensentzug</b>, <b>Eifer</b>.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_3: '<b>Flüchtig</b>,_<b>Giftig</b>.\\nEure anderen Diener\\n haben +1 Angriff.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_4: '<b>Flüchtig</b>,_<b>Giftig</b>.\\nFügt Eurem Helden am Ende Eures_Zuges_3_Schaden_zu.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_5: '<b>Flüchtig</b>,_<b>Giftig</b>.\\nVerdoppelt den Angriff dieses_Dieners zu Beginn Eures_Zuges.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_6: '<b>Flüchtig</b>,_<b>Giftig</b>. Kostet\\n(1) weniger für jeden befreundeten_Diener.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_7: '<b>Flüchtig</b>,_<b>Giftig</b>.\\n<b>Kampfschrei:</b>_Ruft eine_Kopie dieses Dieners_herbei.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_8: '<b>Flüchtig</b>,_<b>Giftig</b>.\\n<b>Todesröcheln:</b> Mischt diesen Diener in Euer Deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_3: '<b>Gottesschild</b>, <b>Spott</b>,\\n<b>Lebensentzug</b>, <b>Eifer</b>.\\nEure anderen Diener\\nhaben +1 Angriff.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_4: '<b>Gottesschild</b>, <b>Spott</b>, \\n<b>Lebensentzug</b>, <b>Eifer</b>.\\nFügt Eurem Helden am Ende_Eures_Zuges 3_Schaden_zu.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_5: '<b>Gottesschild</b>, <b>Spott</b>,\\n<b>Lebensentzug</b>, <b>Eifer</b>.\\nVerdoppelt den Angriff dieses_Dieners zu Beginn Eures_Zuges.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_6: '<b>Gottesschild</b>, <b>Spott</b>,\\n<b>Lebensentzug</b>, <b>Eifer</b>.\\nKostet (1) weniger für jeden befreundeten_Diener.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_7: '<b>Gottesschild</b>, <b>Spott</b>,\\n<b>Lebensentzug</b>, <b>Eifer</b>.\\n<b>Kampfschrei: </b>Ruft eine Kopie dieses Dieners herbei.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_8: '[x]<b>Gottesschild</b>, <b>Spott</b>,\\n<b>Lebensentzug</b>, <b>Eifer</b>.\\n<b>Todesröcheln:</b> Mischt diesen\\nDiener in Euer Deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_4: 'Eure anderen Diener haben +1 Angriff. Fügt Eurem Helden am Ende_Eures_Zuges_3_Schaden_zu.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_5: 'Eure anderen Diener haben +1_Angriff. Verdoppelt den Angriff dieses_Dieners zu Beginn Eures_Zuges.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_6: 'Eure anderen Diener haben +1_Angriff._Kostet_(1)_weniger_für jeden_befreundeten_Diener.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_7: 'Eure anderen Diener\\nhaben +1_Angriff.\\n<b>Kampfschrei:</b> Ruft eine Kopie dieses Dieners herbei.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_8: '[x]Eure anderen Diener \\nhaben +1 Angriff.\\n<b>Todesröcheln:</b> Mischt diesen\\nDiener in Euer Deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_5: 'Fügt Eurem Helden am Ende\\nEures Zuges 3 Schaden zu.\\nVerdoppelt den Angriff dieses_Dieners zu Beginn Eures_Zuges.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_6: 'Fügt Eurem Helden am Ende\\nEures Zuges 3_Schaden zu.\\nKostet (1)_weniger für jeden\\nbefreundeten_Diener.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_7: 'Fügt Eurem Helden am Ende\\nEures Zuges 3 Schaden zu.\\n<b>Kampfschrei:</b> Ruft eine Kopie dieses Dieners herbei.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_8: '[x]Fügt Eurem Helden am Ende\\nEures Zuges 3 Schaden zu.\\n<b>Todesröcheln:</b> Mischt diesen\\nDiener in Euer Deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_6: 'Verdoppelt den Angriff dieses\\nDieners zu Beginn Eures Zuges.\\nKostet (1)_weniger für jeden\\nbefreundeten_Diener.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_7: 'Verdoppelt den Angriff dieses\\nDieners zu Beginn Eures Zuges.\\n<b>Kampfschrei:</b> Ruft eine Kopie dieses Dieners herbei.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_8: '[x]Verdoppelt den Angriff dieses\\nDieners zu Beginn Eures Zuges.\\n<b>Todesröcheln:</b> Mischt diesen\\nDiener in Euer Deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_7: 'Kostet (1) weniger für jeden befreundeten Diener.\\n<b>Kampfschrei:</b> Ruft eine Kopie dieses Dieners herbei.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_8: 'Kostet (1) weniger für jeden befreundeten Diener.\\n<b>Todesröcheln:</b> Mischt diesen Diener in Euer Deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_7_8: '[x]<b>Kampfschrei:</b> Ruft eine\\nKopie dieses Dieners herbei.\\n<b>Todesröcheln:</b> Mischt diesen\\nDiener in Euer Deck.\t',
  },
} as const;
