export const localization = {
  gameplayStrings: {
    GALAKROND_ONCE:              '<b>Invoke</b> once to upgrade.',
    GALAKROND_TWICE:             '<b>Invoke</b> twice to upgrade.',
    GAMEPLAY_UNKNOWN_CREATED_BY: 'another card',
  },
  keywordNames: [
    'Taunt',
    'Freeze',
    'Honorable Kill',
    'Arcane Spell Damage',
    'Fire Spell Damage',
    'Frost Spell Damage',
    'Nature Spell Damage',
    'Holy Spell Damage',
    'Shadow Spell Damage',
    'Fel Spell Damage',
    'Physical Spell Damage',
    'Blood Gem',
    'Windfury',
    'Deathrattle',
    'Combo',
    'Overload: X',
    'Silence',
    'Counter',
    'Immune',
    'Auto-cast',
    'Spare Parts',
    'Refresh',
    'Avenge (X)',
    'Arcane Resistance',
    'Spell Damage',
    'Inspire',
    'Fire Resistance',
    'Frost Resistance',
    'Nature Resistance',
    'Holy Resistance',
    'Shadow Resistance',
    'Fel Resistance',
    'Arcane Weakness',
    'Fire Weakness',
    'Frost Weakness',
    'Nature Weakness',
    'Discover',
    'Holy Weakness',
    'Shadow Weakness',
    'Fel Weakness',
    'Attack',
    'Spell Combo',
    'C\'Thun, Old God',
    'Deathblow',
    'Bleed',
    'Critical Damage',
    'Root',
    'Alliance',
    'Horde',
    'Refresh',
    'Elves',
    'Colossal +X',
    'Dredge',
    'Revive (X)',
    'Spellcraft',
    'Allied',
    'Heal Power',
    'Infuse',
    'Infused',
    'Minion Type',
    'Freeze',
    'Spell Weakness',
    'Spell Resistance',
    'Corpse',
    'Bench',
    'Explorer',
    'Auto-Attack',
    'Silence',
    'Stealth',
    'Quest',
    'Charge',
    'Finale',
    'Overheal',
    'Manathirst (X)',
    'Reborn',
    'Jade Golem',
    'Putricide\'s Creation',
    'Venomous',
    'Bonus Effects',
    'Get your Buddy',
    'Get 2 Buddies',
    'Elusive',
    'Forge',
    'Forged',
    'Grimy Goons',
    'Titan',
    'Jade Lotus',
    'Kabal',
    'Summoned When Drawn',
    'Consume',
    'Miniaturize',
    'Mini',
    'Quickdraw',
    'Excavate',
    'Divine Shield',
    'Pass',
    'Gigantify',
    'Gigantic',
    'Buddy',
    'Passive',
    'Rogue Tourist',
    'Warlock Tourist',
    'Death Knight Tourist',
    'Quest',
    'Shaman Tourist',
    'Demon Hunter Tourist',
    'Priest Tourist',
    'Hunter Tourist',
    'Warrior Tourist',
    'Druid Tourist',
    'Mage Tourist',
    'Paladin Tourist',
    'Imbue',
    'Dark Gift',
    'Poisonous',
    'Temporary',
    'Starship',
    'Trinket',
    'Boss',
    'Discounted',
    'Bonus Keywords',
    'Protoss',
    'Zerg',
    'Terran',
    'Adapt',
    'Rewind',
    'Kindred',
    'Yamato Cannon',
    'Advanced Ballistics',
    'Caduceus Reactor',
    'Fabled',
    'Fabled+',
    'Elemental Bonus',
    'Tavern Spell Bonus',
    'Rally',
    'Shatter',
    'Shattered',
    'Herald',
    'Bounty',
    'Lifesteal',
    'Prepare',
    'Recruit',
    'Timewarp',
    'Refresh Count',
    'Charge',
    'Provoke',
    'Pirate Bonus',
    'Fodders in Refresh',
    'Chromadrake',
    'Fodder',
    'Preparing',
    'Prepared',
    'Secret',
    'Echo',
    'Rush',
    'Passive',
    'Stealth',
    'Overkill',
    'Start of Game',
    'Wild',
    'Magnetic',
    'Enrage',
    'Lackey',
    'Casts When Drawn',
    'Flobbidinous Floop',
    'Shrine',
    'Twinspell',
    'Mega-Windfury',
    'Reborn',
    'Invoke',
    'Battlecry',
    'Invoke: Priest',
    'Invoke: Rogue',
    'Invoke: Shaman',
    'Invoke: Warlock',
    'Invoke: Warrior',
    'Fatigue',
    'Outcast',
    'Spellburst',
    'Sidequest',
    'Frozen',
    'Corrupt',
    'Dormant',
    'Tool',
    'Questline',
    'Tradeable',
    'Corrupted',
    'Frenzy',
  ],
  heraldNames: {
    GAMEPLAY_HERALD_WARRIOR:     'Ragnaros',
    GAMEPLAY_HERALD_DEMONHUNTER: 'Azshara',
    GAMEPLAY_HERALD_SHAMAN:      'Al\'Akir',
    GAMEPLAY_HERALD_ROGUE:       'Sinestra',
    GAMEPLAY_HERALD_DEATHKNIGHT: 'Onyxia',
    GAMEPLAY_HERALD_WARLOCK:     'Cho\'gall',
    GAMEPLAY_HERALD_DEFAULT:     'your Colossal',
  },
  gameplayBuilderStrings: {
    GAMEPLAY_DIAMOND_SPELLSTONE_1:     '<i>(Cast 4 spells to upgrade.)</i>',
    GAMEPLAY_PEARL_SPELLSTONE_1:       '<i>(Restore 3 Health to upgrade.)</i>',
    GAMEPLAY_SAPPHIRE_SPELLSTONE_1:    '<i>(<b>Overload</b> 3 Mana Crystals to upgrade.)</i>',
    GAMEPLAY_JASPER_SPELLSTONE_1:      '<i>(Gain 3 Armor to upgrade.)</i>',
    GAMEPLAY_AMETHYST_SPELLSTONE_1:    '<i>(Take damage from your cards to upgrade.)</i>',
    GAMEPLAY_RUBY_SPELLSTONE_1:        '<i>(Play 2 Elementals to_upgrade.)</i>',
    GAMEPLAY_ONYX_SPELLSTONE_1:        '<i>(Play 3 <b>Deathrattle</b> cards to upgrade.)</i>',
    GAMEPLAY_LOOT_526d_DARKNESS_1:     'When your opponent\\ndraws 3 Candles, this awakens!',
    GAMEPLAY_TOT_109t_STASIS_DRAGON_1: 'This awakens with <b>Rush</b> after two turns.',
    GAMEPLAY_TRLA_TROLL_SHRINE_1:      'Turns until this\\nrevives: 3.',
  },
  raceNames: {
    normal: {
      1:   'Blood Elf',
      2:   'Draenei',
      3:   'Dwarf',
      4:   'Gnome',
      5:   'Goblin',
      6:   'Human',
      7:   'Night Elf',
      8:   'Orc',
      9:   'Tauren',
      10:  'Troll',
      11:  'Undead',
      12:  'Worgen',
      14:  'Murloc',
      15:  'Demon',
      16:  'Scourge',
      17:  'Mech',
      18:  'Elemental',
      19:  'Ogre',
      20:  'Beast',
      21:  'Totem',
      22:  'Nerubian',
      23:  'Pirate',
      24:  'Dragon',
      26:  'All',
      38:  'Egg',
      43:  'Quilboar',
      80:  'Centaur',
      81:  'Furbolg',
      83:  'High Elf',
      84:  'Treant',
      85:  'Owlkin',
      88:  'Half-Orc',
      89:  'Lock',
      92:  'Naga',
      93:  'Old God',
      94:  'Pandaren',
      95:  'Gronn',
      96:  'Celestial',
      97:  'Gnoll',
      98:  'Golem',
      99:  'Harpy',
      100: 'Vulpera',
    },
    battlegrounds: {
      1:  'Blood Elves',
      2:  'Draenei',
      3:  'Dwarves',
      4:  'Gnomes',
      5:  'Goblins',
      6:  'Humans',
      7:  'Night Elves',
      8:  'Orcs',
      9:  'Tauren',
      10: 'Trolls',
      11: 'Undead',
      12: 'Worgen',
      14: 'Murlocs',
      15: 'Demons',
      16: 'Scourge',
      17: 'Mechs',
      18: 'Elementals',
      19: 'Ogres',
      20: 'Beasts',
      21: 'Totems',
      22: 'Nerubians',
      23: 'Pirates',
      24: 'Dragons',
      26: 'Amalgams',
      38: 'Eggs',
      43: 'Quilboar',
      92: 'Naga',
    },
  },
  classNames: {
    1:  'Death Knight',
    2:  'Druid',
    3:  'Hunter',
    4:  'Mage',
    5:  'Paladin',
    6:  'Priest',
    7:  'Rogue',
    8:  'Shaman',
    9:  'Warlock',
    10: 'Warrior',
    12: 'Neutral',
    14: 'Demon Hunter',
  },
  zilliaxCombinedModuleTexts: {
    ZILLIAX_DELUXE_COMBINED_MODULE_1_2: '<b>Elusive</b>, <b>Poisonous</b>, <b>Divine Shield</b>, <b>Taunt</b>, <b>Lifesteal</b>, <b>Rush</b>',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_3: '<b>Elusive</b>, <b>Poisonous</b> \\nYour other minions\\nhave +1 Attack.',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_4: '[x]<b>Elusive</b>, <b>Poisonous</b>\\nAt the end of your turn, deal\\n_3 damage to your hero.',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_5: '[x]<b>Elusive</b>, <b>Poisonous</b>\\nAt the start of your turn, double\\nthis minion\'s Attack.',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_6: '<b>Elusive</b>, <b>Poisonous</b>\\nCosts (1) less for each friendly minion.',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_7: '<b>Elusive</b>, <b>Poisonous</b>\\n<b>Battlecry:</b> Summon\\na copy of this.',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_8: '[x]<b>Elusive</b>, <b>Poisonous</b>\\n<b>Deathrattle:</b> Shuffle this\\ninto your deck.',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_3: '<b>Divine Shield</b>, <b>Taunt</b>,\\n<b>Lifesteal</b>, <b>Rush</b>\\nYour other minions\\nhave +1 Attack.',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_4: '[x]<b>Divine Shield</b>, <b>Taunt</b>,\\n<b>Lifesteal</b>, <b>Rush</b>\\nAt the end of your turn, deal\\n_3 damage to your hero.',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_5: '[x]<b>Divine Shield</b>, <b>Taunt</b>,\\n<b>Lifesteal</b>, <b>Rush</b>\\nAt the start of your turn, double\\nthis minion\'s Attack.',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_6: '<b>Divine Shield</b>, <b>Taunt</b>,\\n<b>Lifesteal</b>, <b>Rush</b>\\nCosts (1) less for each friendly minion.',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_7: '<b>Divine Shield</b>, <b>Taunt</b>,\\n<b>Lifesteal</b>, <b>Rush</b>\\n<b>Battlecry:</b> Summon\\na copy of this.',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_8: '[x]<b>Divine Shield</b>, <b>Taunt</b>,\\n<b>Lifesteal</b>, <b>Rush</b>\\n<b>Deathrattle:</b> Shuffle this\\ninto your deck.',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_4: '[x]Your other minions\\nhave +1 Attack.\\nAt the end of your turn, deal\\n_3 damage to your hero.',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_5: '[x]Your other minions\\nhave +1 Attack.\\nAt the start of your turn, double\\nthis minion\'s Attack.',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_6: '[x]Your other minions\\nhave +1 Attack.\\nCosts (1) less for each\\n friendly minion.',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_7: '[x]Your other minions\\nhave +1 Attack.\\n<b>Battlecry:</b> Summon a\\ncopy of this.',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_8: '[x]Your other minions\\nhave +1 Attack.\\n<b>Deathrattle:</b> Shuffle this\\ninto your deck.',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_5: '[x]At the end of your turn,\\ndeal 3 damage to your hero.\\nAt the start of your turn, double\\nthis minion\'s Attack.',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_6: '[x]At the end of your turn,\\ndeal 3 damage to your hero.\\nCosts (1) less for each\\n friendly minion.',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_7: 'At the end of your turn,\\ndeal 3 damage to your hero.\\n<b>Battlecry:</b> Summon a\\ncopy of this.',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_8: '[x]At the end of your turn,\\ndeal 3 damage to your hero.\\n<b>Deathrattle:</b> Shuffle this\\ninto your deck.',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_6: '[x]At the start of your turn,\\ndouble this minion\'s Attack.\\nCosts (1) less for each\\nfriendly minion.',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_7: 'At the start of your turn,\\ndouble this minion\'s Attack.\\n<b>Battlecry:</b> Summon a\\ncopy of this.',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_8: '[x]At the start of your turn,\\ndouble this minion\'s Attack.\\n<b>Deathrattle:</b> Shuffle this\\ninto your deck.',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_7: 'Costs (1) less for each friendly minion.\\n<b>Battlecry:</b> Summon a\\ncopy of this.',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_8: '[x]Costs (1) less for each\\nfriendly minion.\\n<b>Deathrattle:</b> Shuffle this\\ninto your deck.',
    ZILLIAX_DELUXE_COMBINED_MODULE_7_8: '[x]<b>Battlecry:</b> Summon\\na copy of this.\\n<b>Deathrattle:</b> Shuffle this\\ninto your deck.',
  },
} as const;
