export const localization = {
  gameplayStrings: {
    GALAKROND_ONCE:              '<b>Convoca</b> una vez para mejorarlo.',
    GALAKROND_TWICE:             '<b>Convoca</b> dos veces para mejorarlo.',
    GAMEPLAY_UNKNOWN_CREATED_BY: 'otra carta',
  },
  keywordNames: [
    'Provocar',
    'Congelación',
    'Muerte con honor',
    'Daño con hechizos Arcanos',
    'Daño con hechizos de Fuego',
    'Daño con hechizos de Escarcha',
    'Daño con hechizos de Naturaleza',
    'Daño con hechizos Sagrados',
    'Daño con hechizos de las Sombras',
    'Daño con hechizos Viles',
    'Daño con hechizos físicos',
    'Gema de sangre',
    'Viento furioso',
    'Último aliento',
    'Combo',
    'Sobrecarga: X',
    'Silencio',
    'Contrarrestar',
    'Inmune',
    'Lanzamiento automático',
    'Piezas de repuesto',
    'Refrescar',
    'Vengar a (X)',
    'Resistencia a lo Arcano',
    'Daño con hechizos',
    'Inspirar',
    'Resistencia al Fuego',
    'Resistencia a la Escarcha',
    'Resistencia a la Naturaleza',
    'Resistencia Sagrada',
    'Resistencia a las Sombras',
    'Resistencia vil',
    'Debilidad Arcana',
    'Debilidad al Fuego',
    'Debilidad a la Escarcha',
    'Debilidad a la Naturaleza',
    'Descubre',
    'Debilidad a lo Sagrado',
    'Debilidad a las Sombras',
    'Debilidad vil',
    'Ataque',
    'Combo de hechizo',
    'C\'Thun, dios antiguo',
    'Letal',
    'Sangrar',
    'Daño crítico',
    'Enraizar',
    'Alianza',
    'Horda',
    'Reponer',
    'Elfos',
    'Colosal +X',
    'Draga',
    'Revive (X)',
    'Hechicería',
    'Aliado',
    'Poder de sanación',
    'Imbuir',
    'Imbuida',
    'Tipo de esbirro',
    'Congelación',
    'Debilidad a hechizos',
    'Resistencia a hechizos',
    'Cadáver',
    'Banquillo',
    'Expedicionario',
    'Autoataque',
    'Silenciar',
    'Sigilo',
    'Misión',
    'Cargar',
    'Desenlace',
    'Sobrecuración',
    'Sed de maná (X)',
    'Renacer',
    'Gólem de jade',
    'Creación de Putricidio',
    'Ponzoña',
    'Efectos adicionales',
    'Consigue a tu colega',
    'Consigue dos colegas',
    'Esquivo',
    'Forja',
    'Forjado',
    'Matones Mugrientos',
    'Titán',
    'Loto de Jade',
    'Kabal',
    'Se invoca al robarla',
    'Consumir',
    'Miniaturizar',
    'Mini',
    'Robo rápido',
    'Excavar',
    'Escudo divino',
    'Pasar',
    'Gigantificar',
    'Gigantificado',
    'Colega',
    'Pasivo',
    'Pícaro Turista',
    'Brujo Turista',
    'Caballero de la Muerte turista',
    'Misión',
    'Chamán Turista',
    'Cazador de demonios turista',
    'Sacerdote Turista',
    'Cazador Turista',
    'Guerrero Turista',
    'Druida Turista',
    'Mago Turista',
    'Paladín Turista',
    'Intensifica',
    'Don siniestro',
    'Veneno',
    'Temporal',
    'Nave',
    'Abalorio',
    'Jefe',
    'Con descuento',
    'Palabras clave adicionales',
    'Protoss',
    'Zerg',
    'Terran',
    'Adaptación',
    'Rebobinar',
    'Afinidad',
    'Cañón yamato',
    'Balística avanzada',
    'Reactor caduceo',
    'Renombre',
    'Renombre+',
    'Bonificación de elemental',
    'Bonificación de hechizo de taberna',
    'Alentar',
    'Destrozar',
    'Destrozada',
    'Proclama',
    'Contrato',
    'Robo de vida',
    'Preparar',
    'Recluta',
    'Asincronía',
    'Cantidad de refrescares',
    'Cargar',
    'Burlar',
    'Bonificación pirata',
    'Aperitivos en el Refrescar',
    'Cromadraco',
    'Aperitivo',
    'Preparándose',
    'Preparada',
    'Secreto',
    'Eco',
    'Embestir',
    'Pasivo',
    'Sigilo',
    'Arrasar',
    'Inicio de partida',
    'Salvaje',
    'Magnetismo',
    'Enfurecer',
    'Lacayo',
    'Este hechizo se lanza al robarlo',
    'Flema Salívez',
    'Efigie',
    'Hechizo doble',
    'Megaviento furioso',
    'Renacer',
    'Convoca',
    'Grito de batalla',
    'Convoca: sacerdote',
    'Convoca: pícaro',
    'Convoca: chamán',
    'Convoca: brujo',
    'Convoca: guerrero',
    'Fatiga',
    'Proscrito',
    'Magia súbita',
    'Misión secundaria',
    'Congelado',
    'Corrupción',
    'Letargo',
    'Herramienta',
    'Cadena',
    'Comerciable',
    'Corrupta',
    'Frenesí',
  ],
  heraldNames: {
    GAMEPLAY_HERALD_WARRIOR:     'Ragnaros',
    GAMEPLAY_HERALD_DEMONHUNTER: 'Azshara',
    GAMEPLAY_HERALD_SHAMAN:      'Al\'Akir',
    GAMEPLAY_HERALD_ROGUE:       'Sinestra',
    GAMEPLAY_HERALD_DEATHKNIGHT: 'Onyxia',
    GAMEPLAY_HERALD_WARLOCK:     'Cho\'gall',
    GAMEPLAY_HERALD_DEFAULT:     'tu Colosal',
  },
  gameplayBuilderStrings: {
    GAMEPLAY_DIAMOND_SPELLSTONE_1:     '<i>(Lanza 4 hechizos para mejorarlo).</i>',
    GAMEPLAY_PEARL_SPELLSTONE_1:       '<i>(Restaura 3 p. de salud para mejorarla).</i>',
    GAMEPLAY_SAPPHIRE_SPELLSTONE_1:    '<i>(<b>Sobrecarga</b> 3 cristales de maná para mejorarlo).</i>',
    GAMEPLAY_JASPER_SPELLSTONE_1:      '<i>(Obtén 3 p. de armadura para mejorarlo).</i>',
    GAMEPLAY_AMETHYST_SPELLSTONE_1:    '<i>(Recibe daño de tus cartas para mejorarla).</i>',
    GAMEPLAY_RUBY_SPELLSTONE_1:        '<i>(Juega 2 elementales para mejorarlo).</i>',
    GAMEPLAY_ONYX_SPELLSTONE_1:        '<i>(Juega 3 cartas con <b>Último aliento</b> para mejorarlo).</i>',
    GAMEPLAY_LOOT_526d_DARKNESS_1:     '¡Cuando tu oponente\\nrobe 3 velas, este esbirro se despertará!',
    GAMEPLAY_TOT_109t_STASIS_DRAGON_1: 'Se despierta con <b>Embestir</b> tras dos turnos.',
    GAMEPLAY_TRLA_TROLL_SHRINE_1:      'Turnos hasta\\nque reviva: 3.',
  },
  raceNames: {
    normal: {
      1:   'Elfo de sangre',
      2:   'Draenei',
      3:   'Enano',
      4:   'Gnomo',
      5:   'Goblin',
      6:   'Humano',
      7:   'Elfo de la noche',
      8:   'Orco',
      9:   'Tauren',
      10:  'Trol',
      11:  'No-muerto',
      12:  'Huargen',
      14:  'Múrloc',
      15:  'Demonio',
      16:  'Plaga',
      17:  'Robot',
      18:  'Elemental',
      19:  'Ogro',
      20:  'Bestia',
      21:  'Tótem',
      22:  'Nerubiano',
      23:  'Pirata',
      24:  'Dragón',
      26:  'Todos',
      38:  'Huevo',
      43:  'Jabaespín',
      80:  'Centauro',
      81:  'Fúrbolg',
      83:  'Elfo noble',
      84:  'Antárbol',
      85:  'Búhico',
      88:  'Semiorco',
      89:  'Cerradura',
      92:  'Naga',
      93:  'Dios antiguo',
      94:  'Pandaren',
      95:  'Gronn',
      96:  'Celestial',
      97:  'Gnoll',
      98:  'Gólem',
      99:  'Arpía',
      100: 'Vulpera',
    },
    battlegrounds: {
      1:  'Elfos de sangre',
      2:  'Draenei',
      3:  'Enanos',
      4:  'Gnomos',
      5:  'Goblins',
      6:  'Humanos',
      7:  'Elfos de la noche',
      8:  'Orcos',
      9:  'Tauren',
      10: 'Trols',
      11: 'No-muertos',
      12: 'Huargen',
      14: 'Múrlocs',
      15: 'Demonios',
      16: 'Plaga',
      17: 'Robots',
      18: 'Elementales',
      19: 'Ogros',
      20: 'Bestias',
      21: 'Tótems',
      22: 'Nerubianos',
      23: 'Piratas',
      24: 'Dragones',
      26: 'Amalgamas',
      38: 'Huevos',
      43: 'Jabaespín',
      92: 'Naga',
    },
  },
  classNames: {
    1:  'Caballero de la Muerte',
    2:  'Druida',
    3:  'Cazador',
    4:  'Mago',
    5:  'Paladín',
    6:  'Sacerdote',
    7:  'Pícaro',
    8:  'Chamán',
    9:  'Brujo',
    10: 'Guerrero',
    12: 'Neutral',
    14: 'Cazador de demonios',
  },
  zilliaxCombinedModuleTexts: {
    ZILLIAX_DELUXE_COMBINED_MODULE_1_2: '[x]<b>Esquivo</b>, <b>Veneno</b>,\\n__<b>Escudo divino</b>, <b>Provocar</b>,\\n_<b>Robo de vida</b>, <b>Embestir</b>\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_3: '<b>Esquivo</b>, <b>Veneno</b>\\nTus otros esbirros tienen +1_p. de ataque.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_4: '[x]<b>Esquivo</b>, <b>Veneno</b>\\nAl final de tu turno, inflige\\n____3 p. de daño a tu héroe._\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_5: '[x]<b>Esquivo</b>, <b>Veneno</b>\\nAl comienzo de tu turno,\\nduplica los p. de ataque\\nde este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_6: '[x]<b>Esquivo</b>, <b>Veneno</b>\\nCuesta (1) cristal menos\\n_____por cada esbirro amistoso.__\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_7: '[x]<b>Esquivo</b>, <b>Veneno</b>\\n<b>Grito de batalla:</b> Invoca\\n____una copia de este esbirro.__\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_8: '[x]<b>Esquivo</b>, <b>Veneno</b>\\n<b>Último aliento:</b> Mete este\\nesbirro en tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_3: '<b>Escudo divino</b>, <b>Provocar</b>,\\n<b>Robo de vida</b>, <b>Embestir</b>\\nTus otros esbirros tienen\\n+1_p._de_ataque.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_4: '[x]<b>Escudo divino</b>, <b>Provocar</b>,\\n<b>Robo de vida</b>, <b>Embestir</b>\\nAl final de tu turno, inflige\\n____3 p. de daño a tu héroe._\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_5: '<b>Escudo divino</b>, <b>Provocar</b>,\\n<b>Robo de vida</b>, <b>Embestir</b>\\nAl comienzo de tu turno, duplica_los p. de ataque de_este_esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_6: '<b>Escudo divino</b>, <b>Provocar</b>,\\n<b>Robo de vida</b>, <b>Embestir</b>\\nCuesta (1) cristal menos por_cada_esbirro_amistoso.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_7: '<b>Escudo divino</b>, <b>Provocar</b>,\\n<b>Robo de vida</b>, <b>Embestir</b>\\n<b>Grito de batalla:</b> Invoca\\n__una copia de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_8: '[x]<b>Escudo divino</b>, <b>Provocar</b>,\\n<b>Robo de vida</b>, <b>Embestir</b>\\n<b>Último aliento:</b> Mete este\\nesbirro en tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_4: 'Tus otros esbirros tienen +1_p. de ataque. Al final de tu turno, inflige 3 p. de daño a tu héroe.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_5: 'Tus otros esbirros tienen +1_p. de ataque. Al comienzo de tu turno, duplica los p. de ataque de este_esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_6: 'Tus otros esbirros tienen +1 p. de ataque. Cuesta (1) cristal_menos\\npor_cada esbirro_amistoso.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_7: 'Tus otros esbirros tienen\\n+1 p. de ataque.\\n<b>Grito de batalla:</b> Invoca una copia de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_8: 'Tus otros esbirros tienen\\n+1 p. de ataque.\\n<b>Último_aliento:</b> Mete este esbirro_en tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_5: 'Al final de tu turno, inflige 3 p. de_daño a tu héroe. Al comienzo de_tu turno, duplica los p. de ataque de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_6: 'Al final de tu turno, inflige 3_p._de daño a tu héroe. Cuesta (1) cristal menos por_cada_esbirro_amistoso.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_7: 'Al final de tu turno, inflige 3_p._de_daño a tu héroe.\\n<b>Grito de batalla:</b> Invoca una copia de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_8: 'Al final de tu turno, inflige 3_p._de daño a tu héroe.\\n<b>Último_aliento:</b> Mete este esbirro en tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_6: 'Al comienzo de tu turno,\\nduplica los p. de ataque de este_esbirro. Cuesta (1) cristal menos_por_cada_esbirro_amistoso.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_7: 'Al comienzo de tu turno, duplica los p. de ataque de este esbirro. <b>Grito de batalla:</b> Invoca una copia de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_8: 'Al comienzo de tu turno, duplica los p. de ataque de este esbirro. <b>Último aliento:</b> Mete este esbirro en tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_7: 'Cuesta (1) cristal menos por_cada esbirro amistoso.\\n<b>Grito de batalla:</b> Invoca una copia de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_8: 'Cuesta (1) cristal menos por_cada esbirro amistoso.\\n<b>Último aliento:</b> Mete este esbirro_en tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_7_8: '<b>Grito de batalla:</b> Invoca una copia de este esbirro.\\n<b>Último aliento:</b> Mete este esbirro_en tu mazo.\t',
  },
} as const;
