export const localization = {
  gameplayStrings: {
    GALAKROND_ONCE:              '<b>Conjurez</b> une fois pour l’améliorer.',
    GALAKROND_TWICE:             '<b>Conjurez</b> deux fois pour l’améliorer.',
    GAMEPLAY_UNKNOWN_CREATED_BY: 'une autre carte',
  },
  keywordNames: [
    'Provocation',
    'Gel',
    'Victoire honorable',
    'Dégâts des sorts des arcanes',
    'Dégâts des sorts de feu',
    'Dégâts des sorts de givre',
    'Dégâts des sorts de nature',
    'Dégâts des sorts du sacré',
    'Dégâts des sorts d’ombre',
    'Dégâts des sorts de fiel',
    'Dégâts des sorts physiques',
    'Gemme de sang',
    'Furie des vents',
    'Râle d’agonie',
    'Combo',
    'Surcharge : X',
    'Silence',
    'Contre',
    'Insensible',
    'Lancement auto.',
    'Pièces détachées',
    'Actualiser',
    'Vengeance (X)',
    'Résistance aux Arcanes',
    'Dégâts des sorts',
    'Exaltation',
    'Résistance au Feu',
    'Résistance au Givre',
    'Résistance à la Nature',
    'Résistance au Sacré',
    'Résistance à l’Ombre',
    'Résistance au Fiel',
    'Faiblesse aux Arcanes',
    'Faiblesse au Feu',
    'Faiblesse au Givre',
    'Faiblesse à la Nature',
    'Découverte',
    'Faiblesse au Sacré',
    'Faiblesse à l’Ombre',
    'Faiblesse au Fiel',
    'Attaque',
    'Combo de sorts',
    'C’Thun, Dieu très ancien',
    'Coup de grâce',
    'Saignement',
    'Dégâts critiques',
    'Immobilisation',
    'Alliance',
    'Horde',
    'Réinitialiser',
    'Elfes',
    'Colossal : +X',
    'Dragage',
    'Ranimation (X)',
    'Sorcellerie',
    'Allié',
    'Puissance des soins',
    'Imprégnation',
    'Imprégné',
    'Type de serviteur',
    'Gel',
    'Faiblesse aux sorts',
    'Résistance aux sorts',
    'Cadavre',
    'Réserve',
    'Explorateur',
    'Attaque automatique',
    'Silence',
    'Camouflage',
    'Quête',
    'Charge',
    'Final',
    'Surplus de soins',
    'Soif de mana (X)',
    'Réincarnation',
    'Golem de jade',
    'Création de Putricide',
    'Venimosité',
    'Effets bonus',
    'Recrutez votre compagnon.',
    'Recrutez deux compagnons.',
    'Insaisissable',
    'Forge',
    'Forgé(e)',
    'Les Dessoudeurs',
    'Titan',
    'Lotus de jade',
    'Kabale',
    'Serviteur invoqué dès qu’il est pioché',
    'Engloutir',
    'Miniaturisation',
    'Figurine',
    'Bonne pioche',
    'Déterrer',
    'Bouclier divin',
    'Passer',
    'Gigantification',
    'Gigantesque',
    'Compagnon',
    'Effet passif',
    'Tourisme : voleur',
    'Tourisme : démoniste',
    'Tourisme : chevalier de la mort',
    'Quête',
    'Tourisme : chaman',
    'Tourisme : chasseur de démons',
    'Tourisme : prêtre',
    'Tourisme : chasseur',
    'Tourisme : guerrier',
    'Tourisme : druide',
    'Tourisme : mage',
    'Tourisme : paladin',
    'Empreinte',
    'Sombre don',
    'Toxicité',
    'Temporaire',
    'Vaisseau',
    'Bibelot',
    'Boss',
    'En promotion',
    'Mots-clés bonus',
    'Protoss',
    'Zerg',
    'Terran',
    'Adaptation',
    'Rembobinage',
    'Parenté',
    'Canon Yamato',
    'Balistique avancée',
    'Réacteur Caduceus',
    'Icône',
    'Icône+',
    'Bonus élémentaire',
    'Bonus aux sorts de la taverne',
    'Ralliement',
    'Scission',
    'Carte scindée',
    'Convocation',
    'Prime',
    'Vol de vie',
    'Préparation',
    'Appeler',
    'Chronodistorsion',
    'Actualiser le décompte',
    'Charge',
    'Incitation',
    'Bonus pirate',
    'Chairs à démon en cours d’actualisation',
    'Chromadrake',
    'Chair à démon',
    'En préparation',
    'Préparation',
    'Secret',
    'Écho',
    'Ruée',
    'Passif',
    'Camouflage',
    'Brutalité',
    'Début de partie',
    'Libre',
    'Magnétisme',
    'Accès de rage',
    'Laquais',
    'Jouée quand piochée',
    'Floup le Flasquagineux',
    'Sanctuaire',
    'Sort double',
    'Méga Furie des vents',
    'Réincarnation',
    'Conjurer',
    'Cri de guerre',
    'Conjurer : prêtre',
    'Conjurer : voleur',
    'Conjurer : chaman',
    'Conjurer : démoniste',
    'Conjurer : guerrier',
    'Fatigue',
    'Marginal',
    'Salve',
    'Quête annexe',
    'Gelé',
    'Corruption',
    'En sommeil',
    'Outil',
    'Suite de quêtes',
    'Échangeable',
    'Corrompu',
    'Frénésie',
  ],
  heraldNames: {
    GAMEPLAY_HERALD_WARRIOR:     'Ragnaros',
    GAMEPLAY_HERALD_DEMONHUNTER: 'Azshara',
    GAMEPLAY_HERALD_SHAMAN:      'Al’Akir',
    GAMEPLAY_HERALD_ROGUE:       'Sinestra',
    GAMEPLAY_HERALD_DEATHKNIGHT: 'Onyxia',
    GAMEPLAY_HERALD_WARLOCK:     'Cho’gall',
    GAMEPLAY_HERALD_DEFAULT:     'votre serviteur colossal',
  },
  gameplayBuilderStrings: {
    GAMEPLAY_DIAMOND_SPELLSTONE_1:     '<i>(Lancez 4_sorts pour l’améliorer.)</i>',
    GAMEPLAY_PEARL_SPELLSTONE_1:       '<i>(Rendez 3_PV pour l’améliorer.)</i>',
    GAMEPLAY_SAPPHIRE_SPELLSTONE_1:    '<i>(<b>Surchargez</b> 3_cristaux de mana pour l’améliorer.)</i>',
    GAMEPLAY_JASPER_SPELLSTONE_1:      '<i>(Obtenez 3_points d’armure pour l’améliorer.)</i>',
    GAMEPLAY_AMETHYST_SPELLSTONE_1:    '<i>(S’améliore quand vos cartes vous infligent des dégâts.)</i>',
    GAMEPLAY_RUBY_SPELLSTONE_1:        '<i>(Jouez 2_élémentaires pour l’améliorer.)</i>',
    GAMEPLAY_ONYX_SPELLSTONE_1:        '<i>(Jouez 3_cartes avec <b>Râle d’agonie</b> pour l’améliorer.)</i>',
    GAMEPLAY_LOOT_526d_DARKNESS_1:     'Votre adversaire doit piocher\\n3_bougies pour qu’elles s’éveillent.',
    GAMEPLAY_TOT_109t_STASIS_DRAGON_1: 'Se réveille avec <b>Ruée</b> au bout de deux tours.',
    GAMEPLAY_TRLA_TROLL_SHRINE_1:      'Tours avant\\nréactivation :_3.',
  },
  raceNames: {
    normal: {
      1:   'Elfe de sang',
      2:   'Draeneï',
      3:   'Nain',
      4:   'Gnome',
      5:   'Gobelin',
      6:   'Humain',
      7:   'Elfe de la nuit',
      8:   'Orc',
      9:   'Tauren',
      10:  'Troll',
      11:  'Mort-vivant',
      12:  'Worgen',
      14:  'Murloc',
      15:  'Démon',
      16:  'Fléau',
      17:  'Méca',
      18:  'Élémentaire',
      19:  'Ogre',
      20:  'Bête',
      21:  'Totem',
      22:  'Nérubien',
      23:  'Pirate',
      24:  'Dragon',
      26:  'Tout',
      38:  'Œuf',
      43:  'Huran',
      80:  'Centaure',
      81:  'Furbolg',
      83:  'Haut-Elfe',
      84:  'Tréant',
      85:  'Chouettide',
      88:  'Demi-Orc',
      89:  'Verrouiller',
      92:  'Naga',
      93:  'Dieu très ancien',
      94:  'Pandarens',
      95:  'Gronns',
      96:  'Astre',
      97:  'Gnoll',
      98:  'Golem',
      99:  'Harpie',
      100: 'Vulpérin',
    },
    battlegrounds: {
      1:  'Elfes de sang',
      2:  'Draeneï',
      3:  'Nains',
      4:  'Gnomes',
      5:  'Gobelins',
      6:  'Humains',
      7:  'Elfes de la nuit',
      8:  'Orcs',
      9:  'Taurens',
      10: 'Trolls',
      11: 'Morts-vivants',
      12: 'Worgens',
      14: 'Murlocs',
      15: 'Démons',
      16: 'Fléau',
      17: 'Mécas',
      18: 'Élémentaires',
      19: 'Ogres',
      20: 'Bêtes',
      21: 'Totems',
      22: 'Nérubiens',
      23: 'Pirates',
      24: 'Dragons',
      26: 'Amalgames',
      38: 'Œufs',
      43: 'Hurans',
      92: 'Naga',
    },
  },
  classNames: {
    1:  'Chevalier de la mort',
    2:  'Druide',
    3:  'Chasseur',
    4:  'Mage',
    5:  'Paladin',
    6:  'Prêtre',
    7:  'Voleur',
    8:  'Chaman',
    9:  'Démoniste',
    10: 'Guerrier',
    12: 'Neutre',
    14: 'Chasseur de démons',
  },
  zilliaxCombinedModuleTexts: {
    ZILLIAX_DELUXE_COMBINED_MODULE_1_2: '<b>Insaisissable</b>, <b>Toxicité</b>, <b>Bouclier divin</b>, <b>Provocation</b>, <b>Vol de vie</b>, <b>Ruée</b>\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_3: '<b>Insaisissable</b>, <b>Toxicité</b>\\nVos autres serviteurs\\nont_+1_ATQ.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_4: '[x]<b>Insaisissable</b>,\\n<b>Toxicité</b>\\nÀ la fin de votre tour,\\nvotre héros ou héroïne subit\\n3_points de dégâts.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_5: '[x]<b>Insaisissable</b>,\\n<b>Toxicité</b>\\nAu début de votre tour,\\ndouble l’ATQ de\\nce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_6: '<b>Insaisissable</b>, <b>Toxicité</b>\\nCoûte_(1)_|4(cristal,cristaux)\\nde moins pour chaque\\nserviteur allié.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_7: '<b>Insaisissable</b>, <b>Toxicité</b>\\n<b>Cri de guerre_:</b> invoque\\nune copie de ce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_8: '[x]<b>Insaisissable</b>, <b>Toxicité</b>\\n<b>Râle d’agonie_:</b> place ce serviteur\\ndans votre deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_3: '<b>Bouclier divin</b>, <b>Provocation</b>\\n<b>Vol de vie</b>, <b>Ruée</b>\\nVos autres serviteurs\\nont +1_ATQ.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_4: '[x]<b>Bouclier divin</b>, <b>Provocation</b>\\n<b>Vol de vie</b>, <b>Ruée</b>\\nÀ la fin de votre tour,\\nvotre héros ou héroïne subit\\n3_points de dégâts.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_5: '[x]<b>Bouclier divin</b>, <b>Provocation</b>\\n<b>Vol de vie</b>, <b>Ruée</b>\\nAu début de votre tour,\\ndouble l’Attaque de\\nce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_6: '<b>Bouclier divin</b>, <b>Provocation</b>\\n<b>Vol de vie</b>, <b>Ruée</b>\\nCoûte_(1)_|4(cristal,cristaux) de moins pour chaque serviteur allié.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_7: '<b>Bouclier divin</b>, <b>Provocation</b>\\n<b>Vol de vie</b>, <b>Ruée</b>\\n<b>Cri de guerre_:</b> invoque une copie de ce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_8: '[x]<b>Bouclier divin</b>, <b>Provocation</b>\\n<b>Vol de vie</b>, <b>Ruée</b>\\n<b>Râle d’agonie_:</b> place ce serviteur\\ndans votre deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_4: '[x]Vos autres serviteurs\\nont +1_ATQ.\\nÀ la fin de votre tour,\\nvotre héros ou héroïne subit\\n3_points de dégâts.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_5: '[x]Vos autres serviteurs\\nont +1_ATQ.\\nAu début de votre tour, double\\nl’ATQ de ce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_6: '[x]Vos autres serviteurs\\nont +1_ATQ.\\nCoûte (1)_|4(cristal,cristaux) de moins\\npour chaque serviteur allié.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_7: '[x]Vos autres serviteurs\\nont +1_ATQ.\\n<b>Cri de guerre_:</b> invoque\\nune copie de ce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_8: '[x]Vos autres serviteurs\\nont_+1_ATQ.\\n<b>Râle d’agonie_:</b> place ce serviteur\\ndans votre deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_5: '[x]À la fin de votre tour,\\nvotre héros ou héroïne subit\\n3_points de dégâts. Au début de\\nvotre tour, double l’ATQ\\nde ce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_6: '[x]À la fin de votre tour, votre\\nhéros ou héroïne subit\\n3_points de dégâts.\\nCoûte_(1)_|4(cristal,cristaux) de moins pour\\nchaque serviteur allié.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_7: 'À la fin de votre tour,\\nvotre héros ou héroïne subit\\n3_points de dégâts.\\n<b>Cri de guerre_:</b> invoque une\\ncopie de ce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_8: '[x]À la fin de votre tour,\\nvotre héros ou héroïne subit\\n3_points de dégâts.\\n<b>Râle d’agonie_:</b> place ce\\nserviteur dans votre deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_6: '[x]Au début de votre tour,\\ndouble l’ATQ de ce serviteur.\\nCoûte_(1)_|4(cristal,cristaux) de moins pour\\nchaque serviteur allié.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_7: 'Au début de votre tour,\\ndouble l’ATQ de ce serviteur.\\n<b>Cri de guerre_:</b> invoque une copie de ce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_8: '[x]Au début de votre tour,\\ndouble l’ATQ de ce serviteur.\\n<b>Râle d’agonie_:</b> place ce\\nserviteur dans votre deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_7: 'Coûte_(1)_|4(cristal,cristaux) de moins pour chaque serviteur allié.\\n<b>Cri de guerre_:</b> invoque une copie de ce serviteur.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_8: '[x]Coûte_(1)_|4(cristal,cristaux) de moins pour\\nchaque serviteur allié.\\n<b>Râle d’agonie_:</b> place ce\\nserviteur dans votre deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_7_8: '<b>Cri de guerre_:</b> invoque\\nune copie de ce serviteur.\\n<b>Râle d’agonie_:</b> place ce\\nserviteur dans votre deck.\t',
  },
} as const;
