export const localization = {
  gameplayStrings: {
    GALAKROND_ONCE:              '<b>Invoca</b> una volta per potenziare.',
    GALAKROND_TWICE:             '<b>Invoca</b> due volte per potenziare.',
    GAMEPLAY_UNKNOWN_CREATED_BY: 'un\'altra carta',
  },
  keywordNames: [
    'Provocazione',
    'Congelamento',
    'Uccisione Onorevole',
    'Danni Magici da Arcano',
    'Danni Magici da Fuoco',
    'Danni Magici da Gelo ',
    'Danni Magici da Natura',
    'Danni Magici da Sacro',
    'Danni Magici da Ombra',
    'Danni Magici da Vile',
    'Danni Magici da Combattimento',
    'Gemma del Sangue',
    'Furia del Vento',
    'Rantolo di Morte',
    'Combo',
    'Sovraccarico: (X)',
    'Silenzio',
    'Contrasto',
    'Immune',
    'Lancio automatico',
    'Gadget',
    'Ricarica',
    'Vendetta (X)',
    'Resistenza all\'Arcano',
    'Danni Magici',
    'Ispirazione',
    'Resistenza al Fuoco',
    'Resistenza al Gelo',
    'Resistenza alla Natura',
    'Resistenza al Sacro',
    'Resistenza all\'Ombra',
    'Resistenza al Vile',
    'Debolezza all\'Arcano',
    'Debolezza al Fuoco',
    'Debolezza al Gelo',
    'Debolezza alla Natura',
    'Rinvenimento',
    'Debolezza al Sacro',
    'Debolezza all\'Ombra',
    'Debolezza al Vile',
    'Attacco',
    'Combo Magica',
    'C\'thun, Dio Antico',
    'Colpo di Grazia',
    'Sanguinamento',
    'Danni Critici',
    'Immobilizzazione',
    'Alleanza',
    'Orda',
    'Ricarica',
    'Elfi',
    'Colosso +X',
    'Dragaggio',
    'Resurrezione (X)',
    'Genesi Magica',
    'Alleato',
    'Potere Curativo',
    'Infusione',
    'Infuso',
    'Tipo di servitore',
    'Congelamento',
    'Debolezza alla Magia',
    'Resistenza alla Magia',
    'Cadavere',
    'Panchina',
    'Esploratore',
    'Azione Automatica',
    'Silenzio',
    'Furtività',
    'Missione',
    'Carica',
    'Finale',
    'Sovracura',
    'Sete di Mana (X)',
    'Rinascita',
    'Golem di Giada',
    'Creazione di Putricidio',
    'Fiele',
    'Effetti Bonus',
    'Ottieni il tuo Amico',
    'Ottieni 2 Amici',
    'Elusività',
    'Forgia',
    'Forgiato',
    'Sgherri Torvi',
    'Titano',
    'Loto di Giada',
    'Kabala',
    'Evocato quando pescato',
    'Consuma',
    'Miniaturizza',
    'Mini',
    'Mano Lesta',
    'Dissotterra',
    'Scudo Divino',
    'Passa',
    'Ingigantisci',
    'Gigantesco',
    'Amico',
    'Passivo',
    'Turista nella classe Ladro',
    'Turista nella classe Stregone',
    'Turista nella classe Cavaliere della Morte',
    'Missione',
    'Turista nella classe Sciamano',
    'Turista nella classe Cacciatore di Demoni',
    'Turista nella classe Sacerdote',
    'Turista nella classe Cacciatore',
    'Turista nella classe Guerriero',
    'Turista nella classe Druido',
    'Turista nella classe Mago',
    'Turista nella classe Paladino',
    'Intensifica',
    'Dono Oscuro',
    'Veleno',
    'Temporanea',
    'Astronave',
    'Monile',
    'Boss',
    'Scontato',
    'Abilità bonus',
    'Protoss',
    'Zerg',
    'Terran',
    'Adattamento',
    'Riavvolgimento',
    'Affine',
    'Cannone Yamato',
    'Balistica Avanzata',
    'Reattore Caduceo',
    'Favoloso',
    'Favoloso+',
    'Bonus Elementale',
    'Bonus Magia della Locanda',
    'Adunata',
    'Spaccatura',
    'Carta Spaccata',
    'Proclamazione',
    'Taglia',
    'Furto Vitale',
    'Predisposizione',
    'Reclutamento',
    'Crono-distorsione',
    'Conteggio Ricariche',
    'Carica',
    'Istigazione',
    'Bonus Pirati',
    'Carni da Macello in ricarica',
    'Draco Cromatico',
    'Carne da Macello',
    'Predisposizione in Corso',
    'Predisposizione avvenuta',
    'Segreto',
    'Eco',
    'Assalto',
    'Passivo',
    'Furtività',
    'Annientamento',
    'Inizio Partita',
    'Selvagge',
    'Magnetismo',
    'Rabbia',
    'Lacchè',
    'Lancio Quando Pescata',
    'Melmo il Melmoide',
    'Santuario',
    'Magia Gemella',
    'Super Furia del Vento',
    'Rinascita',
    'Invocazione',
    'Grido di Battaglia',
    'Invocazione: Sacerdote',
    'Invocazione: Ladro',
    'Invocazione: Sciamano',
    'Invocazione: Stregone',
    'Invocazione: Guerriero',
    'Fatica',
    'Ripudio',
    'Impulso Magico',
    'Missione Secondaria',
    'Congelato',
    'Corruzione',
    'Dormiente',
    'Ferri del Mestiere',
    'Serie di Missioni',
    'Scambio',
    'Corrotta',
    'Frenesia',
  ],
  heraldNames: {
    GAMEPLAY_HERALD_WARRIOR:     'Ragnaros',
    GAMEPLAY_HERALD_DEMONHUNTER: 'Azshara',
    GAMEPLAY_HERALD_SHAMAN:      'Al\'Akir',
    GAMEPLAY_HERALD_ROGUE:       'Sinestra',
    GAMEPLAY_HERALD_DEATHKNIGHT: 'Onyxia',
    GAMEPLAY_HERALD_WARLOCK:     'Cho\'gall',
    GAMEPLAY_HERALD_DEFAULT:     'il tuo Colosso',
  },
  gameplayBuilderStrings: {
    GAMEPLAY_DIAMOND_SPELLSTONE_1:     '<i>(Si potenzia lanciando 4 Magie)</i>',
    GAMEPLAY_PEARL_SPELLSTONE_1:       '<i>(Si potenzia rigenerando 3 Salute)</i>',
    GAMEPLAY_SAPPHIRE_SPELLSTONE_1:    '<i>(Si potenzia <b>Sovraccaricando</b> 3 Cristalli di Mana)</i>',
    GAMEPLAY_JASPER_SPELLSTONE_1:      '\\n<i>(Si potenzia ottenendo 3_Armatura)</i>',
    GAMEPLAY_AMETHYST_SPELLSTONE_1:    '<i>(Si potenzia subendo danni dalle tue carte)</i>',
    GAMEPLAY_RUBY_SPELLSTONE_1:        '<i>(Si potenzia giocando due Elementali)</i>',
    GAMEPLAY_ONYX_SPELLSTONE_1:        '<i>(Si potenzia giocando 3 carte con <b>Rantolo di Morte</b>)</i>',
    GAMEPLAY_LOOT_526d_DARKNESS_1:     'Si risveglia quando l\'avversario pesca\\n3 Candele!',
    GAMEPLAY_TOT_109t_STASIS_DRAGON_1: 'Tra due turni, si risveglia con <b>Assalto</b>.',
    GAMEPLAY_TRLA_TROLL_SHRINE_1:      'Torna in vita\\nfra 3 turni.',
  },
  raceNames: {
    normal: {
      1:   'Elfo del Sangue',
      2:   'Draenei',
      3:   'Nano',
      4:   'Gnomo',
      5:   'Goblin',
      6:   'Umano',
      7:   'Elfo della Notte',
      8:   'Orco',
      9:   'Tauren',
      10:  'Troll',
      11:  'Non Morto',
      12:  'Worgen',
      14:  'Murloc',
      15:  'Demone',
      16:  'Flagello',
      17:  'Robot',
      18:  'Elementale',
      19:  'Ogre',
      20:  'Bestia',
      21:  'Totem',
      22:  'Nerubiano',
      23:  'Pirata',
      24:  'Drago',
      26:  'Tutti',
      38:  'Uovo',
      43:  'Verrospino',
      80:  'Centauro',
      81:  'Mezzorso',
      83:  'Alto Elfo',
      84:  'Treant',
      85:  'Gufoide',
      88:  'Mezz\'orco',
      89:  'Blocco',
      92:  'Naga',
      93:  'Dio Antico',
      94:  'Pandaren',
      95:  'Gronn',
      96:  'Celestiale',
      97:  'Gnoll',
      98:  'Golem',
      99:  'Arpia',
      100: 'Vulpera',
    },
    battlegrounds: {
      1:  'Elfi del Sangue',
      2:  'Draenei',
      3:  'Nani',
      4:  'Gnomi',
      5:  'Goblin',
      6:  'Umani',
      7:  'Elfi della Notte',
      8:  'Orchi',
      9:  'Tauren',
      10: 'Troll',
      11: 'Non Morti',
      12: 'Worgen',
      14: 'Murloc',
      15: 'Demoni',
      16: 'Flagello',
      17: 'Robot',
      18: 'Elementali',
      19: 'Ogre',
      20: 'Bestie',
      21: 'Totem',
      22: 'Nerubiani',
      23: 'Pirati',
      24: 'Draghi',
      26: 'Amalgami',
      38: 'Uova',
      43: 'Verrospino',
      92: 'Naga',
    },
  },
  classNames: {
    1:  'Cavaliere della Morte',
    2:  'Druido',
    3:  'Cacciatore',
    4:  'Mago',
    5:  'Paladino',
    6:  'Sacerdote',
    7:  'Ladro',
    8:  'Sciamano',
    9:  'Stregone',
    10: 'Guerriero',
    12: 'Generiche',
    14: 'Cacciatore di Demoni',
  },
  zilliaxCombinedModuleTexts: {
    ZILLIAX_DELUXE_COMBINED_MODULE_1_2: '<b>Elusività</b>. <b>Veleno</b>. <b>Scudo Divino</b>. <b>Provocazione</b>. <b>Furto Vitale</b>. <b>Assalto</b>.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_3: '<b>Elusività</b>. <b>Veleno</b>.\\nGli altri tuoi servitori\\nhanno +1 Attacco.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_4: '<b>Elusività</b>. <b>Veleno</b>. Alla fine del tuo turno, infligge 3_danni al tuo eroe.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_5: '<b>Elusività</b>. <b>Veleno</b>.\\nAll\'inizio del tuo turno, raddoppia l\'Attacco\\ndi questo servitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_6: '<b>Elusività</b>. <b>Veleno</b>.\\nCosta (1) in meno per ogni_tuo servitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_7: '<b>Elusività</b>. <b>Veleno</b>.\\n<b>Grido di Battaglia:</b>\\nevoca una copia\\ndi se stesso.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_8: '[x]<b>Elusività</b>. <b>Veleno</b>.\\n<b>Rantolo di Morte:</b> torna\\nnel tuo mazzo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_3: '<b>Scudo Divino</b>. <b>Provocazione</b>.\\n<b>Furto Vitale</b>. <b>Assalto</b>.\\nGli altri tuoi servitori\\nhanno +1_Attacco.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_4: '<b>Scudo Divino</b>. <b>Provocazione</b>. <b>Furto Vitale</b>. <b>Assalto</b>. Alla fine del tuo turno, infligge _3 danni al tuo eroe.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_5: '<b>Scudo Divino</b>. <b>Provocazione</b>. <b>Furto_Vitale</b>. <b>Assalto</b>. All\'inizio del tuo turno, raddoppia l’Attacco di questo servitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_6: '<b>Scudo Divino</b>. <b>Provocazione</b>. <b>Furto Vitale</b>. <b>Assalto</b>. Costa (1) in meno per ogni tuo servitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_7: '<b>Scudo Divino</b>.\\n<b>Provocazione</b>. <b>Furto Vitale</b>. <b>Assalto</b>. <b>Grido_di_Battaglia:</b> evoca una copia di\\nse stesso.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_8: '<b>Scudo Divino</b>.\\n<b>Provocazione</b>. <b>Furto Vitale</b>. <b>Assalto</b>. <b>Rantolo di Morte:</b> torna nel tuo mazzo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_4: 'Gli altri tuoi servitori\\nhanno +1 Attacco. Alla fine del\\ntuo turno, infligge 3 danni al_tuo_eroe.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_5: 'Gli altri tuoi servitori\\nhanno +1 Attacco. All\'inizio del\\ntuo turno, raddoppia l\'Attacco di questo servitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_6: 'Gli altri tuoi servitori\\nhanno +1 Attacco. Costa (1)\\nin meno per ogni tuo\\nservitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_7: 'Gli altri tuoi servitori hanno +1 Attacco. <b>Grido di Battaglia:</b> evoca una copia di se stesso.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_8: 'Gli altri tuoi servitori\\nhanno +1 Attacco. <b>Rantolo di Morte:</b> torna nel tuo mazzo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_5: '[x]Alla fine del tuo turno,\\ninfligge 3 danni al tuo eroe.\\nAll\'inizio del tuo turno, raddoppia\\nl’Attacco di questo servitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_6: '[x]Alla fine del tuo turno,\\ninfligge 3 danni al tuo eroe.\\nCosta (1) in meno per ogni\\ntuo servitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_7: 'Alla fine del tuo turno,\\ninfligge 3 danni al tuo eroe.\\n<b>Grido di Battaglia:</b> evoca una copia di questo servitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_8: '[x]Alla fine del tuo turno,\\ninfligge 3 danni al tuo eroe.\\n<b>Rantolo di Morte:</b> torna\\nnel tuo mazzo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_6: 'All\'inizio del tuo turno, raddoppia l\'Attacco di questo servitore. Costa (1) in meno per ogni tuo servitore.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_7: 'All\'inizio del tuo turno,\\nraddoppia l’Attacco di questo servitore. <b>Grido di Battaglia:</b> evoca una copia di\\nse stesso.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_8: '[x]All\'inizio del tuo turno,\\nraddoppia l’Attacco di questo servitore.\\n<b>Rantolo di Morte:</b> torna\\nnel tuo mazzo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_7: 'Costa (1) in meno per\\nogni tuo servitore.\\n<b>Grido di Battaglia:</b> evoca\\nuna copia di se stesso.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_8: '[x]Costa (1) in meno per\\nogni tuo servitore.\\n<b>Rantolo di Morte:</b> torna\\nnel tuo mazzo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_7_8: '[x]<b>Grido di Battaglia:</b> evoca\\nuna copia di se stesso.\\n<b>Rantolo di Morte:</b> torna\\nnel tuo mazzo.\t',
  },
} as const;
