export const localization = {
  gameplayStrings: {
    GALAKROND_ONCE:              '<b>Convoca</b> una vez para mejorar esta carta.',
    GALAKROND_TWICE:             '<b>Convoca</b> dos veces para mejorar esta carta.',
    GAMEPLAY_UNKNOWN_CREATED_BY: 'otra carta',
  },
  keywordNames: [
    'Provocación',
    'Congelar',
    'Muerte con honor',
    'Daño de hechizo Arcano',
    'Daño de hechizo de Fuego',
    'Daño de hechizo de Escarcha',
    'Daño de hechizo de Naturaleza',
    'Daño de hechizo Sagrado',
    'Daño de hechizo de las Sombras',
    'Daño de hechizo Vil',
    'Daño de hechizo Físico',
    'Gema de sangre',
    'Viento furioso',
    'Estertor',
    'Combo',
    'Sobrecarga: X',
    'Silenciar',
    'Contrarrestar',
    'Inmune',
    'Autolanzamiento',
    'Piezas de repuesto',
    'Renovar',
    'Vengar (X)',
    'Resistencia a lo Arcano',
    'Daño de hechizo',
    'Inspirar',
    'Resistencia al Fuego',
    'Resistencia a la Escarcha',
    'Resistencia a la Naturaleza',
    'Resistencia a lo Sagrado',
    'Resistencia a las Sombras',
    'Resistencia a lo Vil',
    'Debilidad a lo Arcano',
    'Debilidad al Fuego',
    'Debilidad a la Escarcha',
    'Debilidad a la Naturaleza',
    'Develar',
    'Debilidad a lo Sagrado',
    'Debilidad a las Sombras',
    'Debilidad a lo Vil',
    'Ataque',
    'Combo de hechizos',
    'C\'Thun, dios antiguo',
    'Golpe letal',
    'Sangrado',
    'Daño crítico',
    'Enraizado',
    'Alianza',
    'Horda',
    'Restablecer',
    'Elfos',
    'Colosal +X',
    'Dragar',
    'Revivir (X)',
    'Hechicería',
    'Aliado',
    'Poder de sanación',
    'Infundir',
    'Infundido',
    'Tipo de esbirro',
    'Congelar',
    'Debilidad a los hechizos',
    'Resistencia a los hechizos',
    'Cadáver',
    'Banca',
    'Expedicionario',
    'Ataque automático',
    'Silenciar',
    'Sigilo',
    'Misión',
    'Carga',
    'Gran final',
    'Sobresanación',
    'Sed de maná (X)',
    'Renacer',
    'Gólem de jade',
    'Creación de Putricidio',
    'Tóxico',
    'Efectos adicionales',
    'Obtén tu Compa',
    'Obtén 2 Compas',
    'Evasivo',
    'Forjar',
    'Forjado',
    'Matones malosos',
    'Titán',
    'Loto de jade',
    'Kabal',
    'Se invoca al robarlo',
    'Consumir',
    'Miniaturizar',
    'Mini',
    'Desenfundar',
    'Excavar',
    'Escudo divino',
    'Pasar',
    'Gigantificación',
    'Gigantesco',
    'Compa',
    'Pasivo',
    'Pícaro Turista',
    'Brujo Turista',
    'Caballero de la muerte Turista',
    'Misión',
    'Chamán Turista',
    'Cazador de demonios Turista',
    'Sacerdote Turista',
    'Cazador Turista',
    'Guerrero Turista',
    'Druida Turista',
    'Mago Turista',
    'Paladín Turista',
    'Imbuir',
    'Regalo oscuro',
    'Venenoso',
    'Temporal',
    'Nave estelar',
    'Abalorio',
    'Jefe',
    'Con descuento',
    'Bonificación de palabras clave',
    'Protoss',
    'Zerg',
    'Terran',
    'Adapta',
    'Rebobinar',
    'Afinidad',
    'Cañón Yamato',
    'Balística avanzada',
    'Reactor caduceo',
    'Célebre',
    'Célebre+',
    'Bonificación elemental',
    'Bonificación de hechizo de la Taberna',
    'Alentar',
    'Destrozar',
    'Destrozado',
    'Proclamar',
    'Botín',
    'Robavida',
    'Preparar',
    'Recluta',
    'Cronoanomalía',
    'Contador de Renovar',
    'Carga',
    'Provocar',
    'Bonificación pirata',
    'Carroñas en Renovar',
    'Cromadraco',
    'Carroña',
    'Preparándose',
    'Preparado',
    'Secreto',
    'Eco',
    'Acometida',
    'Pasivo',
    'Sigilo',
    'Arrasar',
    'Inicio de la partida',
    'Salvaje',
    'Magnetismo',
    'Enfurecer',
    'Lacayo',
    'Se juega al robarla',
    'Mucus Muquitinoso',
    'Santuario',
    'Hechizo doble',
    'Megaviento furioso',
    'Renacer',
    'Convocar',
    'Grito de batalla',
    'Convocar: Sacerdote',
    'Convocar: Pícaro',
    'Convocar: Chamán',
    'Convocar: Brujo',
    'Convocar: Guerrero',
    'Fatiga',
    'Marginado',
    'Magia súbita',
    'Misión secundaria',
    'Congelado',
    'Corrupción',
    'Dormido',
    'Herramienta',
    'Serie de misiones',
    'Intercambiable',
    'Corrupto',
    'Frenesí',
  ],
  heraldNames: {
    GAMEPLAY_HERALD_WARRIOR:     'Ragnaros',
    GAMEPLAY_HERALD_DEMONHUNTER: 'Azshara',
    GAMEPLAY_HERALD_SHAMAN:      'Al\'Akir',
    GAMEPLAY_HERALD_ROGUE:       'Sinestra',
    GAMEPLAY_HERALD_DEATHKNIGHT: 'Onyxia',
    GAMEPLAY_HERALD_WARLOCK:     'Cho\'gall',
    GAMEPLAY_HERALD_DEFAULT:     'tu Colosal',
  },
  gameplayBuilderStrings: {
    GAMEPLAY_DIAMOND_SPELLSTONE_1:     '<i>(Juega 4 hechizos para mejorar esta carta).</i>',
    GAMEPLAY_PEARL_SPELLSTONE_1:       '<i>(Restaura 3 de Salud para mejorar esta carta).</i>',
    GAMEPLAY_SAPPHIRE_SPELLSTONE_1:    '<i>(<b>Sobrecarga</b> 3 Cristales de maná para mejorar esta carta).</i>',
    GAMEPLAY_JASPER_SPELLSTONE_1:      '<i>(Obtén 3 de Armadura para mejorar esta carta).</i>',
    GAMEPLAY_AMETHYST_SPELLSTONE_1:    '<i>(Recibe daño de tus cartas para mejorar esta carta).</i>',
    GAMEPLAY_RUBY_SPELLSTONE_1:        '<i>(Juega 2 Elementales para mejorar esta carta).</i>',
    GAMEPLAY_ONYX_SPELLSTONE_1:        '<i>(Juega 3 cartas con <b>Estertor</b> para mejorar esta carta).</i>',
    GAMEPLAY_LOOT_526d_DARKNESS_1:     '¡Cuando tu adversario\\nrobe 3 Velas, esta carta se despertará!',
    GAMEPLAY_TOT_109t_STASIS_DRAGON_1: 'Después de dos turnos, despierta y obtiene <b>Acometida</b>.',
    GAMEPLAY_TRLA_TROLL_SHRINE_1:      'Turnos hasta que\\nreviva: 3.',
  },
  raceNames: {
    normal: {
      1:   'Elfo de sangre',
      2:   'Draenei',
      3:   'Enano',
      4:   'Gnomo',
      5:   'Goblin',
      6:   'Humano',
      7:   'Elfo de la noche',
      8:   'Orco',
      9:   'Tauren',
      10:  'Trol',
      11:  'No-muerto',
      12:  'Huargen',
      14:  'Múrloc',
      15:  'Demonio',
      16:  'Plaga',
      17:  'Meca',
      18:  'Elemental',
      19:  'Ogro',
      20:  'Bestia',
      21:  'Tótem',
      22:  'Nerubiano',
      23:  'Pirata',
      24:  'Dragón',
      26:  'Todas',
      38:  'Huevo',
      43:  'Jabaespín',
      80:  'Centauro',
      81:  'Fúrbolg',
      83:  'Elfo noble',
      84:  'Antárbol',
      85:  'Buhíco',
      88:  'Semiorco',
      89:  'Bloquear',
      92:  'Naga',
      93:  'Dios antiguo',
      94:  'Pandaren',
      95:  'Gronn',
      96:  'Celestial',
      97:  'Gnoll',
      98:  'Gólem',
      99:  'Arpía',
      100: 'Vulpera',
    },
    battlegrounds: {
      1:  'Elfos de sangre',
      2:  'Draenei',
      3:  'Enanos',
      4:  'Gnomos',
      5:  'Goblins',
      6:  'Humanos',
      7:  'Elfos de la noche',
      8:  'Orcos',
      9:  'Tauren',
      10: 'Trols',
      11: 'No-muertos',
      12: 'Huargen',
      14: 'Múrlocs',
      15: 'Demonios',
      16: 'Plaga',
      17: 'Mecas',
      18: 'Elementales',
      19: 'Ogros',
      20: 'Bestias',
      21: 'Tótems',
      22: 'Nerubianos',
      23: 'Piratas',
      24: 'Dragones',
      26: 'Amalgamas',
      38: 'Huevos',
      43: 'Jabaespín',
      92: 'Naga',
    },
  },
  classNames: {
    1:  'Caballero de la Muerte',
    2:  'Druida',
    3:  'Cazador',
    4:  'Mago',
    5:  'Paladín',
    6:  'Sacerdote',
    7:  'Pícaro',
    8:  'Chamán',
    9:  'Brujo',
    10: 'Guerrero',
    12: 'Neutral',
    14: 'Cazador de demonios',
  },
  zilliaxCombinedModuleTexts: {
    ZILLIAX_DELUXE_COMBINED_MODULE_1_2: '<b>Evasivo</b>, <b>Venenoso</b>, <b>Escudo_divino</b>, <b>Provocación</b>, <b>Robavida</b>, <b>Acometida</b>\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_3: '<b>Evasivo</b>, <b>Venenoso</b> \\nTus otros esbirros\\ntienen +1_de_Ataque.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_4: '[x]<b>Evasivo</b>, <b>Venenoso</b>\\nAl final de tu turno, inflige\\n_3 de daño a tu héroe.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_5: '[x]<b>Evasivo</b>, <b>Venenoso</b>\\nAl comienzo de tu turno, duplica\\nel Ataque de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_6: '<b>Evasivo</b>, <b>Venenoso</b>\\nCuesta (1) menos por cada esbirro aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_7: '<b>Evasivo</b>, <b>Venenoso</b>\\n<b>Grito de batalla:</b> invoca una_copia de este_esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_8: '[x]<b>Evasivo</b>, <b>Venenoso</b>\\n<b>Estertor:</b> coloca esto\\nen tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_3: '<b>Escudo divino</b>, <b>Provocación</b>,\\n<b>Robavida</b>, <b>Acometida</b>\\nTus otros esbirros\\ntienen +1_de_Ataque.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_4: '[x]<b>Escudo divino</b>, <b>Provocación</b>,\\n<b>Robavida</b>, <b>Acometida</b>\\nAl final de tu turno, inflige\\n_3 de daño a tu héroe.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_5: '[x]<b>Escudo divino</b>, <b>Provocación</b>,\\n<b>Robavida</b>, <b>Acometida</b>\\nAl comienzo de tu turno, duplica\\nel Ataque de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_6: '<b>Escudo divino</b>, <b>Provocación</b>,\\n<b>Robavida</b>, <b>Acometida</b>\\nCuesta (1) menos por cada esbirro aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_7: '<b>Escudo divino</b>, <b>Provocación</b>,\\n<b>Robavida</b>, <b>Acometida</b>\\n<b>Grito de batalla:</b> invoca\\nuna copia de este.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_8: '[x]<b>Escudo divino</b>, <b>Provocación</b>,\\n<b>Robavida</b>, <b>Acometida</b>\\n<b>Estertor:</b> coloca esto\\nen tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_4: '[x]Tus otros esbirros\\ntienen +1 de Ataque.\\nAl final de tu turno, inflige\\n_3 de daño a tu héroe.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_5: '[x]Tus otros esbirros\\ntienen +1 de Ataque.\\nAl comienzo de tu turno, duplica\\nel Ataque de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_6: '[x]Tus otros esbirros\\ntienen +1 de Ataque.\\nCuesta (1) menos por\\ncada esbirro aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_7: '[x]Tus otros esbirros\\ntienen +1 de Ataque.\\n<b>Grito de batalla:</b>_invoca_una\\ncopia de este.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_8: '[x]Tus otros esbirros\\ntienen +1 de Ataque.\\n<b>Estertor:</b> coloca este\\nen tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_5: '[x]Al final de tu turno, inflige\\n3 de daño a tu héroe.\\nAl comienzo de tu turno, duplica\\nel Ataque de este esbirro.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_6: '[x]Al final de tu turno, inflige\\n3 de daño a tu héroe.\\nCuesta (1) menos por\\ncada esbirro aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_7: 'Al final de tu turno, inflige\\n3 de daño a tu héroe.\\n<b>Grito de batalla:</b> invoca\\nuna copia de este.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_8: '[x]Al final de tu turno, inflige\\n3 de daño a tu héroe.\\n<b>Estertor:</b> coloca esto\\nen tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_6: '[x]Al comienzo de tu turno, duplica\\nel Ataque de este esbirro.\\nCuesta (1) menos por\\ncada esbirro aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_7: 'Al comienzo de tu turno, duplica\\nel Ataque de este esbirro.\\n<b>Grito de batalla:</b> invoca\\nuna copia de este.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_8: '[x]Al comienzo de tu turno, duplica\\nel Ataque de este esbirro.\\n<b>Estertor:</b> coloca esto\\nen tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_7: 'Cuesta (1) menos por cada esbirro aliado.\\n<b>Grito de batalla:</b> invoca\\nuna copia de este.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_8: '[x]Cuesta (1) menos por\\ncada esbirro aliado.\\n<b>Estertor:</b> coloca esto\\nen tu mazo.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_7_8: '[x]<b>Grito de batalla:</b> invoca\\nuna copia de este.\\n<b>Estertor:</b> coloca esto\\nen tu mazo.\t',
  },
} as const;
