export const localization = {
  gameplayStrings: {
    GALAKROND_ONCE:              '<b>Inwokuj</b> raz, aby ulepszyć.',
    GALAKROND_TWICE:             '<b>Inwokuj</b>_dwa razy, aby ulepszyć.',
    GAMEPLAY_UNKNOWN_CREATED_BY: 'inna karta',
  },
  keywordNames: [
    'Prowokacja',
    'Zamrożenie',
    'Honorowe zabójstwo',
    'Obrażenia zaklęć Mocy tajemnej',
    'Obrażenia zaklęć Ognia',
    'Obrażenia zaklęć Lodu',
    'Obrażenia zaklęć Natury',
    'Obrażenia zaklęć Świętości',
    'Obrażenia zaklęć Cienia',
    'Obrażenia zaklęć Spaczenia',
    'Obrażenia zaklęć Walki bezpośredniej',
    'Krwawy klejnot',
    'Furia wichru',
    'Agonia',
    'Kombinacja',
    'Przeciążenie: X',
    'Wyciszenie',
    'Kontra',
    'Niewrażliwość',
    'Automatyczne użycie',
    'Części zamienne',
    'Odśwież',
    'Pomsta (X)',
    'Odporność na Moc tajemną',
    'Obrażenia zaklęć',
    'Inspiracja',
    'Odporność na Ogień',
    'Odporność na Lód',
    'Odporność na Naturę',
    'Odporność na Świętość',
    'Odporność na Cień',
    'Odporność na Spaczenie',
    'Wrażliwość na Moc tajemną',
    'Wrażliwość na Ogień',
    'Wrażliwość na Lód',
    'Wrażliwość na Naturę',
    'Odkryj',
    'Wrażliwość na Świętość',
    'Wrażliwość na Cień',
    'Wrażliwość na Spaczenie',
    'Atak',
    'Kombinacja zaklęć',
    'C\'Thun, Przedwieczny Bóg',
    'Cios kończący',
    'Krwawa rana',
    'Krytyczne obrażenia',
    'Zakorzenienie',
    'Przymierze',
    'Horda',
    'Odśwież',
    'Elfy',
    'Kolos +X',
    'Wyłów kartę',
    'Ożywienie (X)',
    'Czarodzieło',
    'Sojusznik',
    'Moc uzdrawiania',
    'Nasyć',
    'Nasycenie',
    'Rodzaj stronnika',
    'Zamrożenie',
    'Wrażliwość na zaklęcia',
    'Odporność na zaklęcia',
    'Trup',
    'Rezerwa',
    'Odkrywca',
    'Automatyczny atak',
    'Wyciszenie',
    'Ukrycie',
    'Zadanie',
    'Szarża',
    'Finał',
    'Naduzdrowienie',
    'Manomania (X)',
    'Odrodzenie',
    'Nefrytowy Golem',
    'Twór Przebrzyda',
    'Jad',
    'Efekty dodatkowe',
    'Zdobądź towarzysza',
    'Zdobądź 2 towarzyszy',
    'Nieuchwytność',
    'Wykuj',
    'Wykucie',
    'Posępne Zbiry',
    'Tytan',
    'Nefrytowy Lotos',
    'Konfraternia',
    'Przyzwanie po dobraniu',
    'Pożryj',
    'Miniaturyzacja',
    'Miniatura',
    'Szybkostrzał',
    'Wykop',
    'Boska tarcza',
    'Przekaż',
    'Gigantyfikacja',
    'Gigant',
    'Towarzysz',
    'Działanie pasywne',
    'Łotr – Turysta',
    'Czarnoksiężnik – Turysta',
    'Rycerz śmierci – Turysta',
    'Zadanie',
    'Szaman – Turysta',
    'Łowca demonów – Turysta',
    'Kapłan – Turysta',
    'Łowca – Turysta',
    'Wojownik – Turysta',
    'Druid – Turysta',
    'Mag – Turysta',
    'Paladyn – Turysta',
    'Przesyć',
    'Mroczny dar',
    'Trucizna',
    'Tymczasowa',
    'Statek kosmiczny',
    'Ozdoba',
    'Boss',
    'Zniżka',
    'Dodatkowe słowa kluczowe',
    'Protosi',
    'Zergi',
    'Terranie',
    'Adaptuj',
    'Cofnięcie',
    'Krewniacy',
    'Działo Yamato',
    'Zaawansowana balistyka',
    'Reaktor Asklepios',
    'Osławieni',
    'Osławieni+',
    'Premia: żywiołak',
    'Premia: zaklęcie z Karczmy',
    'Natchnienie',
    'Rozbicie',
    'Złączenie',
    'Apel',
    'Zlecenie',
    'Kradzież życia',
    'Gotowość',
    'Rekrutuj',
    'Skok czasowy',
    'Liczba Odświeżeń',
    'Szarża',
    'Prowokacja',
    'Premia za Pirata',
    'Pożywki przy Odświeżeniu',
    'Chromasmokowiec',
    'Pożywka',
    'Nabieranie gotowości',
    'W gotowości',
    'Sekret',
    'Echo',
    'Zryw',
    'Pasywne działanie',
    'Ukrycie',
    'Rzeź',
    'Początek gry',
    'Dzicz',
    'Magnetyzm',
    'Szał',
    'Sługus',
    'Zagraj po dobraniu',
    'Fluś Farmiglut',
    'Kapliczka',
    'Dwuczar',
    'Megafuria wichru',
    'Odrodzenie',
    'Inwokuj',
    'Okrzyk bojowy',
    'Inwokuj: Kapłan',
    'Inwokuj: Łotr',
    'Inwokuj: Szaman',
    'Inwokuj: Czarnoksiężnik',
    'Inwokuj: Wojownik',
    'Zmęczenie',
    'Wyrzutek',
    'Erupcja magii',
    'Zadanie poboczne',
    'Zamrożenie',
    'Splugawienie',
    'W stanie uśpienia',
    'Przyrząd',
    'Seria zadań',
    'Wymiana',
    'Splugawieniec',
    'Obłęd',
  ],
  heraldNames: {
    GAMEPLAY_HERALD_WARRIOR:     'Ragnaros',
    GAMEPLAY_HERALD_DEMONHUNTER: 'Aszara',
    GAMEPLAY_HERALD_SHAMAN:      'Al\'Akir',
    GAMEPLAY_HERALD_ROGUE:       'Sinestra',
    GAMEPLAY_HERALD_DEATHKNIGHT: 'Onyxia',
    GAMEPLAY_HERALD_WARLOCK:     'Czo\'gal',
    GAMEPLAY_HERALD_DEFAULT:     'twój Kolos',
  },
  gameplayBuilderStrings: {
    GAMEPLAY_DIAMOND_SPELLSTONE_1:     '<i>(Rzuć 4 zaklęcia, aby ulepszyć.)</i>',
    GAMEPLAY_PEARL_SPELLSTONE_1:       '<i>(Przywróć 3 pkt. zdrowia, aby ulepszyć.)</i>',
    GAMEPLAY_SAPPHIRE_SPELLSTONE_1:    '<i>(<b>Przeciąż</b> 3 kryształy many, aby ulepszyć.)</i>',
    GAMEPLAY_JASPER_SPELLSTONE_1:      '<i>(Otrzymaj 3 pkt. pancerza, aby ulepszyć.)</i>',
    GAMEPLAY_AMETHYST_SPELLSTONE_1:    '<i>(Otrzymaj obrażenia od twoich kart, aby ulepszyć.)</i>',
    GAMEPLAY_RUBY_SPELLSTONE_1:        '<i>(Zagraj 2 Żywiołaki, aby_ulepszyć.)</i>',
    GAMEPLAY_ONYX_SPELLSTONE_1:        '<i>(Zagraj 3 karty z_<b>Agonią</b>, aby ulepszyć.)</i>',
    GAMEPLAY_LOOT_526d_DARKNESS_1:     'Gdy twój przeciwnik dobierze\\ntrzy Świece, Ciemność przebudzi się!',
    GAMEPLAY_TOT_109t_STASIS_DRAGON_1: 'Po dwóch turach obudzi się ze <b>Zrywem</b>.',
    GAMEPLAY_TRLA_TROLL_SHRINE_1:      'Tury do powrotu\\nKapliczki: 3',
  },
  raceNames: {
    normal: {
      1:   'Krwawy Elf',
      2:   'Draenei',
      3:   'Krasnolud',
      4:   'Gnom',
      5:   'Goblin',
      6:   'Człowiek',
      7:   'Nocny Elf',
      8:   'Ork',
      9:   'Tauren',
      10:  'Troll',
      11:  'Nieumarły',
      12:  'Worgen',
      14:  'Murlok',
      15:  'Demon',
      16:  'Plaga',
      17:  'Mech',
      18:  'Żywiołak',
      19:  'Ogr',
      20:  'Bestia',
      21:  'Totem',
      22:  'Nerubianin',
      23:  'Pirat',
      24:  'Smok',
      26:  'Wszystkie',
      38:  'Jajo',
      43:  'Kolcozwierz',
      80:  'Centaur',
      81:  'Furbolg',
      83:  'Wysoki elf',
      84:  'Drzewiec',
      85:  'Sowozwierz',
      88:  'Półork',
      89:  'Blokada',
      92:  'Naga',
      93:  'Przedwieczny bóg',
      94:  'Pandaren',
      95:  'Gronn',
      96:  'Niebianin',
      97:  'Gnol',
      98:  'Golem',
      99:  'Harpia',
      100: 'Lisołaczka',
    },
    battlegrounds: {
      1:  'Krwawe elfy',
      2:  'Draenei',
      3:  'Krasnoludy',
      4:  'Gnomy',
      5:  'Gobliny',
      6:  'Ludzie',
      7:  'Nocne elfy',
      8:  'Orkowie',
      9:  'Taureni',
      10: 'Trolle',
      11: 'Nieumarli',
      12: 'Worgeni',
      14: 'Murloki',
      15: 'Demony',
      16: 'Plaga',
      17: 'Mechy',
      18: 'Żywiołaki',
      19: 'Ogry',
      20: 'Bestie',
      21: 'Totemy',
      22: 'Nerubianie',
      23: 'Piraci',
      24: 'Smoki',
      26: 'Amalgamaty',
      38: 'Jaja',
      43: 'Kolcozwierze',
      92: 'Naga',
    },
  },
  classNames: {
    1:  'Rycerz śmierci',
    2:  'Druid',
    3:  'Łowca',
    4:  'Mag',
    5:  'Paladyn',
    6:  'Kapłan',
    7:  'Łotr',
    8:  'Szaman',
    9:  'Czarnoksiężnik',
    10: 'Wojownik',
    12: 'Neutralne',
    14: 'Łowca demonów',
  },
  zilliaxCombinedModuleTexts: {
    ZILLIAX_DELUXE_COMBINED_MODULE_1_2: '<b>Nieuchwytność</b>, <b>Trucizna</b>, <b>Boska tarcza</b>, <b>Prowokacja</b>, <b>Kradzież życia</b>, <b>Zryw</b>\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_3: '<b>Nieuchwytność</b>, <b>Trucizna</b>\\nTwoi pozostali stronnicy mają +1 do ataku.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_4: '[x]<b>Nieuchwytność</b>, <b>Trucizna</b>\\nNa koniec twojej tury zadaj 3_pkt. obrażeń twojemu bohaterowi.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_5: '[x]<b>Nieuchwytność</b>, <b>Trucizna</b>\\nNa początku twojej tury podwój atak tego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_6: '<b>Nieuchwytność</b>, <b>Trucizna</b>\\nKosztuje (1)_mniej za_każdego przyjaznego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_7: '<b>Nieuchwytność</b>, <b>Trucizna</b>\\n<b>Okrzyk bojowy:</b> Przyzwij_kopię tego_stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_8: '[x]<b>Nieuchwytność</b>, <b>Trucizna</b>\\n<b>Agonia:</b> Wtasuj tę kartę do_twojej talii.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_3: '<b>Boska tarcza</b>, <b>Prowokacja</b>,\\n<b>Kradzież życia</b>, <b>Zryw</b>\\nTwoi pozostali stronnicy mają +1_do ataku.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_4: '[x]<b>Boska tarcza</b>, <b>Prowokacja</b>,\\n<b>Kradzież życia</b>, <b>Zryw</b>\\nNa koniec twojej tury\\nzadaj 3_pkt. obrażeń\\ntwojemu bohaterowi.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_5: '[x]<b>Boska tarcza</b>, <b>Prowokacja</b>,\\n<b>Kradzież życia</b>, <b>Zryw</b>\\nNa początku twojej tury\\npodwój atak\\ntego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_6: '<b>Boska tarcza</b>, <b>Prowokacja</b>,\\n<b>Kradzież życia</b>, <b>Zryw</b>\\nKosztuje (1)_mniej za_każdego przyjaznego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_7: '<b>Boska tarcza</b>, <b>Prowokacja</b>,\\n<b>Kradzież życia</b>, <b>Zryw</b>\\n<b>Okrzyk bojowy:</b> Przyzwij kopię tego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_8: '[x]<b>Boska tarcza</b>, <b>Prowokacja</b>,\\n<b>Kradzież życia</b>, <b>Zryw</b>\\n<b>Agonia:</b> Wtasuj tę kartę\\ndo twojej talii.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_4: '[x]Twoi pozostali stronnicy\\nmają_+1 do ataku.\\nNa koniec twojej tury\\nzadaj 3_pkt. obrażeń\\ntwojemu bohaterowi.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_5: '[x]Twoi pozostali stronnicy\\nmają_+1 do ataku.\\nNa początku twojej tury\\npodwój atak\\ntego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_6: '[x]Twoi pozostali stronnicy\\nmają +1 do ataku.\\nKosztuje (1) mniej za każdego\\nprzyjaznego_stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_7: '[x]Twoi pozostali stronnicy\\nmają_+1 do ataku.\\n<b>Okrzyk bojowy:</b> Przyzwij\\nkopię tego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_8: '[x]Twoi pozostali stronnicy\\nmają_+1 do ataku.\\n<b>Agonia:</b> Wtasuj tę kartę\\ndo twojej talii.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_5: '[x]Na koniec twojej tury zadaj\\n3_pkt. obrażeń twojemu bohaterowi.\\nNa początku twojej tury\\npodwój atak tego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_6: '[x]Na koniec twojej tury\\nzadaj 3 pkt. obrażeń\\ntwojemu bohaterowi.\\nKosztuje (1) mniej za każdego\\nprzyjaznego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_7: 'Na koniec twojej tury zadaj_3_pkt._obrażeń twojemu_bohaterowi.\\n<b>Okrzyk bojowy:</b> Przyzwij kopię tego_stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_8: '[x]Na koniec twojej tury\\nzadaj 3_pkt. obrażeń\\ntwojemu bohaterowi.\\n<b>Agonia:</b> Wtasuj tę kartę\\ndo twojej talii.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_6: '[x]Na początku twojej tury\\npodwój atak tego stronnika.\\nKosztuje (1) mniej za każdego\\nprzyjaznego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_7: 'Na początku twojej tury podwój_atak tego stronnika.\\n<b>Okrzyk bojowy:</b> Przyzwij kopię tego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_8: '[x]Na początku twojej tury\\npodwój atak tego stronnika.\\n<b>Agonia:</b> Wtasuj tę kartę\\ndo twojej talii.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_7: 'Kosztuje (1)_mniej za_każdego przyjaznego stronnika.\\n<b>Okrzyk bojowy:</b> Przyzwij kopię tego stronnika.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_8: '[x]Kosztuje (1) mniej za każdego\\nprzyjaznego stronnika.\\n<b>Agonia:</b> Wtasuj tę kartę\\ndo twojej talii.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_7_8: '[x]<b>Okrzyk bojowy:</b> Przyzwij\\nkopię tego stronnika.\\n<b>Agonia:</b> Wtasuj tę kartę\\ndo twojej talii.\t',
  },
} as const;
