export const localization = {
  gameplayStrings: {
    GALAKROND_ONCE:              '<b>Invoque</b> uma vez para aprimorar.',
    GALAKROND_TWICE:             '<b>Invoque</b> duas vezes para aprimorar.',
    GAMEPLAY_UNKNOWN_CREATED_BY: 'outro card',
  },
  keywordNames: [
    'Provocar',
    'Congelar',
    'Abate Honroso',
    'Dano Mágico Arcano',
    'Dano Mágico de Fogo',
    'Dano Mágico de Gelo',
    'Dano Mágico de Natureza',
    'Dano Mágico Sagrado',
    'Dano Mágico de Sombra',
    'Dano Mágico Vil',
    'Dano Mágico Físico',
    'Gema Sangrenta',
    'Fúria dos Ventos',
    'Último Suspiro',
    'Combo',
    'Sobrecarga: X',
    'Silêncio',
    'Anular',
    'Imune',
    'Lançamento automático',
    'Peças sobressalentes',
    'Atualizar',
    'Vingar (X)',
    'Resistência ao Arcano',
    'Dano Mágico',
    'Inspirar',
    'Resistência ao Fogo',
    'Resistência ao Gelo',
    'Resistência à Natureza',
    'Resistência ao Sagrado',
    'Resistência à Sombra',
    'Resistência a Vileza',
    'Fraqueza Arcana',
    'Fraqueza Ígnea',
    'Fraqueza Gélida',
    'Fraqueza Natural',
    'Descubra',
    'Fraqueza Sagrada',
    'Fraqueza Sombria',
    'Fraqueza Vil',
    'Ataque',
    'Combo de Feitiço',
    'C\'Thun, Deus Antigo',
    'Golpe Fatal',
    'Sangramento',
    'Dano Crítico',
    'Enraizar',
    'Aliança',
    'Horda',
    'Restaurar',
    'Elfos',
    'Colossal +X',
    'Dragar',
    'Reviver (X)',
    'Feitiçaria',
    'Aliado',
    'Poder de Cura',
    'Imbuir',
    'Imbuído',
    'Tipo de Lacaio',
    'Congelar',
    'Fraqueza Mágica',
    'Resistência Mágica',
    'Cadáver',
    'Banco',
    'Explorador',
    'Ataque Automático',
    'Silêncio',
    'Furtividade',
    'Missão',
    'Investida',
    'Finale',
    'Cura Excessiva',
    'Sede de Mana (X)',
    'Renascer',
    'Golem de Jade',
    'Criação do Putricida',
    'Peçonhento',
    'Efeitos Bônus',
    'Receba seu Camarada',
    'Receba 2 Camaradas',
    'Elusivo',
    'Forjar',
    'Forjado',
    'Capangas Cruéis',
    'Titã',
    'Lótus de Jade',
    'Kabal',
    'Evocado quando comprado',
    'Consumir',
    'Miniaturizar',
    'Mini',
    'Saque Rápido',
    'Escavar',
    'Escudo Divino',
    'Passar',
    'GIGANTIZAR!',
    'Gigante!',
    'Camarada',
    'Passivo',
    'Turista: Ladino',
    'Turista: Bruxo',
    'Turista: Cavaleiro da Morte',
    'Missão',
    'Turista: Xamã',
    'Turista: Caçador de Demônios',
    'Turista: Sacerdote',
    'Turista: Caçador',
    'Turista: Guerreiro',
    'Turista: Druida',
    'Turista: Mago',
    'Turista: Paladino',
    'Intensificar',
    'Dádiva Sinistra',
    'Venenoso',
    'Temporário',
    'Nave Estelar',
    'Berloque',
    'Chefe',
    'Com desconto',
    'Palavras-chave de Bônus',
    'Protoss',
    'Zerg',
    'Terrano',
    'Adapte‑se',
    'Retroceder',
    'Afinidade',
    'Canhão Yamato',
    'Balística Avançada',
    'Reator Caduceu',
    'Célebre',
    'Célebre+',
    'Bônus Elemental',
    'Bônus de Feitiço da Taverna',
    'Conclamar',
    'Partir',
    'Partido',
    'Proclamar',
    'Contrato',
    'Roubar Vida',
    'Preparar',
    'Recruta',
    'Distorção Temporal',
    'Atualizar contagem',
    'Investida',
    'Instigar',
    'Bônus Pirata',
    'Comidas ao Atualizar',
    'Cromadraco',
    'Comida',
    'Preparando',
    'Preparado',
    'Segredo',
    'Eco',
    'Rapidez',
    'Passivo',
    'Furtividade',
    'Massacre',
    'Início da Partida',
    'Livre',
    'Magnético',
    'Enfurecer',
    'Servo',
    'Lançado ao Comprar',
    'Flupe Fuzubúrdio',
    'Santuário',
    'Feitiço Duplo',
    'Mega-Fúria dos Ventos',
    'Renascer',
    'Invocar',
    'Grito de Guerra',
    'Invocar: Sacerdote',
    'Invocar: Ladino',
    'Invocar: Xamã',
    'Invocar: Bruxo',
    'Invocar: Guerreiro',
    'Fadiga',
    'Exilar',
    'Sortilégio',
    'Tarefa',
    'Congelado',
    'Corromper',
    'Adormecido',
    'Ferramenta',
    'Série de Missões',
    'Trocável',
    'Corrompido',
    'Frenesi',
  ],
  heraldNames: {
    GAMEPLAY_HERALD_WARRIOR:     'Ragnaros',
    GAMEPLAY_HERALD_DEMONHUNTER: 'Azshara',
    GAMEPLAY_HERALD_SHAMAN:      'Al\'Akir',
    GAMEPLAY_HERALD_ROGUE:       'Sinestra',
    GAMEPLAY_HERALD_DEATHKNIGHT: 'Onyxia',
    GAMEPLAY_HERALD_WARLOCK:     'Cho\'gall',
    GAMEPLAY_HERALD_DEFAULT:     'seu Colossal',
  },
  gameplayBuilderStrings: {
    GAMEPLAY_DIAMOND_SPELLSTONE_1:     '<i>(Lance 4 feitiços para aprimorar.)</i>',
    GAMEPLAY_PEARL_SPELLSTONE_1:       '<i>(Restaure 3 de Vida para aprimorar.)</i>',
    GAMEPLAY_SAPPHIRE_SPELLSTONE_1:    '<i>(Cause <b>Sobrecarga</b> em 3 Cristais de Mana para aprimorar.)</i>',
    GAMEPLAY_JASPER_SPELLSTONE_1:      '<i>(Receba 3 de Armadura para aprimorar.)</i>',
    GAMEPLAY_AMETHYST_SPELLSTONE_1:    '<i>(Receba dano de seus cards para aprimorar.)</i>',
    GAMEPLAY_RUBY_SPELLSTONE_1:        '<i>(Jogue 2 Elementais para aprimorar.)</i>',
    GAMEPLAY_ONYX_SPELLSTONE_1:        '<i>(Jogue 3 cards com <b>Último Suspiro</b> para aprimorar.)</i>',
    GAMEPLAY_LOOT_526d_DARKNESS_1:     'Quando seu oponente\\ncomprar 3 Velas, este lacaio_desperta!',
    GAMEPLAY_TOT_109t_STASIS_DRAGON_1: 'Desperta com <b>Rapidez</b> após dois turnos.',
    GAMEPLAY_TRLA_TROLL_SHRINE_1:      'Turnos até\\nreviver: 3.',
  },
  raceNames: {
    normal: {
      1:   'Elfo Sangrento',
      2:   'Draenei',
      3:   'Anão',
      4:   'Gnomo',
      5:   'Goblin',
      6:   'Humano',
      7:   'Elfo Noturno',
      8:   'Orc',
      9:   'Tauren',
      10:  'Troll',
      11:  'Morto-Vivo',
      12:  'Worgen',
      14:  'Murloc',
      15:  'Demônio',
      16:  'Flagelo',
      17:  'Mecanoide',
      18:  'Elemental',
      19:  'Ogro',
      20:  'Fera',
      21:  'Totem',
      22:  'Nerubiano',
      23:  'Pirata',
      24:  'Dragão',
      26:  'Tudo',
      38:  'Ovo',
      43:  'Javatusco',
      80:  'Centauro',
      81:  'Pelurso',
      83:  'Elfo Superior',
      84:  'Arvoroso',
      85:  'Corujante',
      88:  'Meio Orc',
      89:  'Tranca',
      92:  'Naga',
      93:  'Deus Antigo',
      94:  'Pandaren',
      95:  'Gronn',
      96:  'Celestial',
      97:  'Gnoll',
      98:  'Golem',
      99:  'Harpia',
      100: 'Vulpera',
    },
    battlegrounds: {
      1:  'Elfos Sangrentos',
      2:  'Draenei',
      3:  'Anões',
      4:  'Gnomos',
      5:  'Goblins',
      6:  'Humanos',
      7:  'Elfos Noturnos',
      8:  'Orcs',
      9:  'Taurens',
      10: 'Trolls',
      11: 'Mortos-vivos',
      12: 'Worgens',
      14: 'Murlocs',
      15: 'Demônios',
      16: 'Flagelo',
      17: 'Mecanoides',
      18: 'Elementais',
      19: 'Ogros',
      20: 'Feras',
      21: 'Totens',
      22: 'Nerubianos',
      23: 'Piratas',
      24: 'Dragões',
      26: 'Amálgamas',
      38: 'Ovos',
      43: 'Javatusco',
      92: 'Naga',
    },
  },
  classNames: {
    1:  'Cavaleiro da Morte',
    2:  'Druida',
    3:  'Caçador',
    4:  'Mago',
    5:  'Paladino',
    6:  'Sacerdote',
    7:  'Ladino',
    8:  'Xamã',
    9:  'Bruxo',
    10: 'Guerreiro',
    12: 'Neutro',
    14: 'Caçador de Demônios',
  },
  zilliaxCombinedModuleTexts: {
    ZILLIAX_DELUXE_COMBINED_MODULE_1_2: '<b>Elusivo</b>, <b>Venenoso</b>, <b>Escudo_Divino</b>, <b>Provocar</b>, <b>Roubar_Vida</b>, <b>Rapidez</b>\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_3: '<b>Elusivo</b>, <b>Venenoso</b>\\nSeus outros lacaios têm +1 de Ataque.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_4: '[x]<b>Elusivo</b>, <b>Venenoso</b>\\nNo final do seu turno, cause\\n_3 de dano ao seu herói.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_5: '[x]<b>Elusivo</b>, <b>Venenoso</b>\\nNo início do seu turno, dobre\\no ataque deste lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_6: '<b>Elusivo</b>, <b>Venenoso</b>\\nCusta (1) a menos para cada lacaio aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_7: '<b>Elusivo</b>, <b>Venenoso</b>\\n<b>Grito de Guerra:</b> Evoque uma_cópia_deste_lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_1_8: '[x]<b>Elusivo</b>, <b>Venenoso</b>\\n<b>Último Suspiro:</b> Coloque este\\ncard no seu deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_3: '<b>Escudo Divino</b>, <b>Provocar</b>,\\n<b>Roubar Vida</b>, <b>Rapidez</b>\\nSeus outros lacaios\\ntêm +1 de Ataque.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_4: '[x]<b>Escudo Divino</b>, <b>Provocar</b>,\\n<b>Roubar Vida</b>, <b>Rapidez</b>\\nNo final do seu turno, cause\\n_3 de dano ao seu herói.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_5: '[x]<b>Escudo Divino</b>, <b>Provocar</b>,\\n<b>Roubar Vida</b>, <b>Rapidez</b>\\nNo início do seu turno, dobre\\no Ataque deste lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_6: '<b>Escudo Divino</b>, <b>Provocar</b>,\\n<b>Roubar Vida</b>, <b>Rapidez</b>\\nCusta (1) a menos para cada lacaio aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_7: '<b>Escudo Divino</b>, <b>Provocar</b>,\\n<b>Roubar Vida</b>, <b>Rapidez</b>\\n<b>Grito de Guerra:</b> Evoque\\numa cópia deste lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_2_8: '[x]<b>Escudo Divino</b>, <b>Provocar</b>,\\n<b>Roubar Vida</b>, <b>Rapidez</b>\\n<b>Último Suspiro:</b> Coloque este\\ncard no seu deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_4: '[x]Seus outros lacaios\\ntêm +1 de Ataque.\\nNo final do seu turno, cause\\n_3 de dano ao seu herói.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_5: '[x]Seus outros lacaios\\ntêm +1 de Ataque.\\nNo início do seu turno, dobre\\no Ataque deste lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_6: 'Seus outros lacaios\\ntêm +1 de Ataque.\\nCusta (1) a menos para cada lacaio aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_7: '[x]Seus outros lacaios\\ntêm +1 de Ataque.\\n<b>Grito de Guerra:</b> Evoque uma\\ncópia deste lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_3_8: '[x]Seus outros lacaios\\ntêm +1 de Ataque.\\n<b>Último Suspiro:</b> Coloque este\\ncard no seu deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_5: 'No final do seu turno,\\ncause 3 de dano ao seu herói.\\nNo início do seu turno, dobre o Ataque deste lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_6: 'No final do seu turno,\\ncause 3 de dano ao seu herói.\\nCusta (1) a menos para cada lacaio aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_7: 'No final do seu turno,\\ncause 3 de dano ao seu herói.\\n<b>Grito de Guerra:</b> Evoque uma cópia deste lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_4_8: 'No final do seu turno,\\ncause 3 de dano ao seu herói.\\n<b>Último Suspiro:</b> Coloque este card no seu deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_6: 'No início do seu turno,\\ndobre o Ataque deste lacaio.\\nCusta (1) a menos para cada lacaio aliado.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_7: 'No início do seu turno,\\ndobre o Ataque deste lacaio.\\n<b>Grito de Guerra:</b> Evoque uma cópia deste lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_5_8: 'No início do seu turno,\\ndobre o Ataque deste lacaio.\\n<b>Último Suspiro:</b> Coloque este card no seu deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_7: 'Custa (1) a menos para cada lacaio aliado.\\n<b>Grito de Guerra:</b> Evoque uma cópia deste lacaio.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_6_8: 'Custa (1) a menos para cada lacaio aliado.\\n<b>Último Suspiro:</b> Coloque este card no seu deck.\t',
    ZILLIAX_DELUXE_COMBINED_MODULE_7_8: '<b>Grito de Guerra:</b> Evoque uma cópia deste lacaio.\\n<b>Último Suspiro:</b> Coloque este card no seu deck.\t',
  },
} as const;
