/** Tag slugs. Entries sorted by enum ID ascending. */
export const TAG_SLUG = {
  DATA_NUM_1: 'data-num-1',
  DATA_NUM_2: 'data-num-2',
  PREMIUM: 'premium',
  HIDE_HEALTH: 'hide-health',
  HIDE_ATTACK: 'hide-attack',
  HIDE_COST: 'hide-cost',
  USE_ALTERNATE_CARD_TEXT: 'use-alternate-card-text',
  HIDE_WATERMARK: 'hide-watermark',
  LETTUCE_ROLE: 'mercenary-role',
  LETTUCE_PASSIVE_ABILITY: 'lettuce-passive-ability',
  LETTUCE_ABILITY_SUMMONED_MINION: 'lettuce-ability-summoned-minion',
  TRADEABLE: 'tradeable',
  IN_MINI_SET: 'in-mini-set',
  LETTUCE_MERCENARY_EXPERIENCE: 'lettuce-mercenary-experience',
  LETTUCE_EQUIPMENT: 'lettuce-equipment',
  HAS_DIAMOND: 'has-diamond',
  LETTUCE_IS_TREASURE_CARD: 'lettuce-is-treasure-card',
  LETTUCE_ABILITY_TIER: 'lettuce-ability-tier',
  LETTUCE_EQUIPMENT_TIER: 'lettuce-equipment-tier',
  HAS_SIGNATURE: 'has-signature',
  LETTUCE_FACTION: 'mercenary-faction',
  FORGE: 'forge',
  DATA_NUM_3: 'data-num-3',
  CARD_NAME_DATA_1: 'card-name-data-1',
  DATA_NUM_4: 'data-num-4',
  DATA_NUM_5: 'data-num-5',
  DATA_NUM_6: 'data-num-6',
  PREPARE: 'prepare',
  TIMEWARPED: 'timewarped',
  BACON_ALT_TAVERN_SYSTEM_ACTIVE: 'bacon-alt-tavern-system-active',
  HAS_TIMEWARPED_TAVERN_ALT_TEXT: 'has-timewarped-tavern-alt-text',
} as const;

/** GAME_TAG enum IDs. Keys match TAG_SLUG, sorted by value ascending. */
export const TAG_ID = {
  DATA_NUM_1: 2,
  DATA_NUM_2: 3,
  PREMIUM: 12,
  HIDE_HEALTH: 682,
  HIDE_ATTACK: 683,
  HIDE_COST: 684,
  USE_ALTERNATE_CARD_TEXT: 955,
  HIDE_WATERMARK: 1107,
  LETTUCE_ROLE: 1666,
  LETTUCE_PASSIVE_ABILITY: 1671,
  LETTUCE_ABILITY_SUMMONED_MINION: 1676,
  TRADEABLE: 1720,
  IN_MINI_SET: 1824,
  LETTUCE_MERCENARY_EXPERIENCE: 1852,
  LETTUCE_EQUIPMENT: 1855,
  HAS_DIAMOND: 1932,
  LETTUCE_IS_TREASURE_CARD: 2170,
  LETTUCE_ABILITY_TIER: 2493,
  LETTUCE_EQUIPMENT_TIER: 2494,
  HAS_SIGNATURE: 2589,
  LETTUCE_FACTION: 2720,
  FORGE: 2785,
  DATA_NUM_3: 2889,
  CARD_NAME_DATA_1: 2890,
  DATA_NUM_4: 2919,
  DATA_NUM_5: 2920,
  DATA_NUM_6: 2921,
  PREPARE: 4354,
  TIMEWARPED: 4503,
  BACON_ALT_TAVERN_SYSTEM_ACTIVE: 4519,
  HAS_TIMEWARPED_TAVERN_ALT_TEXT: 4579,
} as const;

/**
 * Render mechanic numeric IDs, sorted ascending.
 * These are the GAME_TAG enum IDs used as keys in renderModel.renderMechanics.
 *
 * Spec: [hearthstone-image-renderer-protocol](../../../../../docs/hearthstone-image-renderer-protocol.md)
 */
export const RENDER_MECHANIC_IDS = [
  String(TAG_ID.DATA_NUM_1),
  String(TAG_ID.DATA_NUM_2),
  String(TAG_ID.HIDE_HEALTH),
  String(TAG_ID.HIDE_ATTACK),
  String(TAG_ID.HIDE_COST),
  String(TAG_ID.USE_ALTERNATE_CARD_TEXT),
  String(TAG_ID.HIDE_WATERMARK),
  String(TAG_ID.LETTUCE_PASSIVE_ABILITY),
  String(TAG_ID.LETTUCE_ABILITY_SUMMONED_MINION),
  String(TAG_ID.TRADEABLE),
  String(TAG_ID.IN_MINI_SET),
  String(TAG_ID.LETTUCE_MERCENARY_EXPERIENCE),
  String(TAG_ID.LETTUCE_EQUIPMENT),
  String(TAG_ID.LETTUCE_IS_TREASURE_CARD),
  String(TAG_ID.LETTUCE_ABILITY_TIER),
  String(TAG_ID.LETTUCE_EQUIPMENT_TIER),
  String(TAG_ID.FORGE),
  String(TAG_ID.DATA_NUM_3),
  String(TAG_ID.CARD_NAME_DATA_1),
  String(TAG_ID.DATA_NUM_4),
  String(TAG_ID.DATA_NUM_5),
  String(TAG_ID.DATA_NUM_6),
  String(TAG_ID.PREPARE),
  String(TAG_ID.TIMEWARPED),
  String(TAG_ID.BACON_ALT_TAVERN_SYSTEM_ACTIVE),
  String(TAG_ID.HAS_TIMEWARPED_TAVERN_ALT_TEXT),
] as const;
