/** Tag slugs. Entries sorted by enum ID ascending. */
export const TAG_SLUG = {
  DATA_NUM_1:                      'data-num-1',
  DATA_NUM_2:                      'data-num-2',
  PREMIUM:                         'premium',
  WINDFURY:                        'windfury',
  TAUNT:                           'taunt',
  STEALTH:                         'stealth',
  DIVINE_SHIELD:                   'divine-shield',
  SCORE_VALUE_1:                   'score-value-1',
  MODULAR_ENTITY_PART_1:           'modular-entity-part-1',
  MODULAR_ENTITY_PART_2:           'modular-entity-part-2',
  QUEST_PROGRESS_TOTAL:            'quest-progress-total',
  HIDE_HEALTH:                     'hide-health',
  HIDE_ATTACK:                     'hide-attack',
  HIDE_COST:                       'hide-cost',
  HIDDEN_CHOICE:                   'hidden-choice',
  MAGNETIC:                        'magnetic',
  USE_ALTERNATE_CARD_TEXT:         'use-alternate-card-text',
  REBORN:                          'reborn',
  HIDE_WATERMARK:                  'hide-watermark',
  BACON_TRIPLED_BASE_MINION_ID:    'bacon-tripled-base-minion-id',
  LETTUCE_ROLE:                    'mercenary-role',
  LETTUCE_PASSIVE_ABILITY:         'lettuce-passive-ability',
  LETTUCE_ABILITY_SUMMONED_MINION: 'lettuce-ability-summoned-minion',
  TRADEABLE:                       'tradeable',
  IN_MINI_SET:                     'in-mini-set',
  LETTUCE_MERCENARY_EXPERIENCE:    'lettuce-mercenary-experience',
  LETTUCE_EQUIPMENT:               'lettuce-equipment',
  HAS_DIAMOND:                     'has-diamond',
  LETTUCE_IS_TREASURE_CARD:        'lettuce-is-treasure-card',
  LETTUCE_ABILITY_TIER:            'lettuce-ability-tier',
  LETTUCE_EQUIPMENT_TIER:          'lettuce-equipment-tier',
  HAS_SIGNATURE:                   'has-signature',
  CARDTEXT_ENTITY_0:               'cardtext-entity-0',
  CARDTEXT_ENTITY_1:               'cardtext-entity-1',
  CARDTEXT_ENTITY_2:               'cardtext-entity-2',
  CARDTEXT_ENTITY_3:               'cardtext-entity-3',
  CARDTEXT_ENTITY_4:               'cardtext-entity-4',
  CARDTEXT_ENTITY_5:               'cardtext-entity-5',
  CARDTEXT_ENTITY_6:               'cardtext-entity-6',
  CARDTEXT_ENTITY_7:               'cardtext-entity-7',
  CARDTEXT_ENTITY_8:               'cardtext-entity-8',
  CARDTEXT_ENTITY_9:               'cardtext-entity-9',
  LETTUCE_FACTION:                 'mercenary-faction',
  FORGE:                           'forge',
  DATA_NUM_3:                      'data-num-3',
  CARD_NAME_DATA_1:                'card-name-data-1',
  DATA_NUM_4:                      'data-num-4',
  DATA_NUM_5:                      'data-num-5',
  DATA_NUM_6:                      'data-num-6',
  HIDDEN_CHOICE_OVERRIDE:          'hidden-choice-override',
  BACON_TRIPLED_BASE_MINION_ID2:   'bacon-tripled-base-minion-id-2',
  BACON_TRIPLED_BASE_MINION_ID3:   'bacon-tripled-base-minion-id-3',
  DYNAMIC_KEYWORD1:                'dynamic-keyword-1',
  DYNAMIC_KEYWORD2:                'dynamic-keyword-2',
  PREPARE:                         'prepare',
  TIMEWARPED:                      'timewarped',
  BACON_ALT_TAVERN_SYSTEM_ACTIVE:  'bacon-alt-tavern-system-active',
  HAS_TIMEWARPED_TAVERN_ALT_TEXT:  'has-timewarped-tavern-alt-text',
} as const;

/** GAME_TAG enum IDs. Keys match TAG_SLUG, sorted by value ascending. */
export const TAG_ID = {
  DATA_NUM_1:                      2,
  DATA_NUM_2:                      3,
  PREMIUM:                         12,
  WINDFURY:                        189,
  TAUNT:                           190,
  STEALTH:                         191,
  DIVINE_SHIELD:                   194,
  SCORE_VALUE_1:                   451,
  MODULAR_ENTITY_PART_1:           471,
  MODULAR_ENTITY_PART_2:           472,
  QUEST_PROGRESS_TOTAL:            535,
  HIDE_HEALTH:                     682,
  HIDE_ATTACK:                     683,
  HIDE_COST:                       684,
  HIDDEN_CHOICE:                   813,
  MAGNETIC:                        849,
  USE_ALTERNATE_CARD_TEXT:         955,
  REBORN:                          1085,
  HIDE_WATERMARK:                  1107,
  BACON_TRIPLED_BASE_MINION_ID:    1471,
  LETTUCE_ROLE:                    1666,
  LETTUCE_PASSIVE_ABILITY:         1671,
  LETTUCE_ABILITY_SUMMONED_MINION: 1676,
  TRADEABLE:                       1720,
  IN_MINI_SET:                     1824,
  LETTUCE_MERCENARY_EXPERIENCE:    1852,
  LETTUCE_EQUIPMENT:               1855,
  HAS_DIAMOND:                     1932,
  LETTUCE_IS_TREASURE_CARD:        2170,
  LETTUCE_ABILITY_TIER:            2493,
  LETTUCE_EQUIPMENT_TIER:          2494,
  HAS_SIGNATURE:                   2589,
  CARDTEXT_ENTITY_0:               2655,
  CARDTEXT_ENTITY_1:               2656,
  CARDTEXT_ENTITY_2:               2657,
  CARDTEXT_ENTITY_3:               2658,
  CARDTEXT_ENTITY_4:               2659,
  CARDTEXT_ENTITY_5:               2660,
  CARDTEXT_ENTITY_6:               2661,
  CARDTEXT_ENTITY_7:               2662,
  CARDTEXT_ENTITY_8:               2663,
  CARDTEXT_ENTITY_9:               2664,
  LETTUCE_FACTION:                 2720,
  FORGE:                           2785,
  DATA_NUM_3:                      2889,
  CARD_NAME_DATA_1:                2890,
  DATA_NUM_4:                      2919,
  DATA_NUM_5:                      2920,
  DATA_NUM_6:                      2921,
  HIDDEN_CHOICE_OVERRIDE:          2946,
  BACON_TRIPLED_BASE_MINION_ID2:   3499,
  BACON_TRIPLED_BASE_MINION_ID3:   3500,
  DYNAMIC_KEYWORD1:                4161,
  DYNAMIC_KEYWORD2:                4162,
  PREPARE:                         4354,
  TIMEWARPED:                      4503,
  BACON_ALT_TAVERN_SYSTEM_ACTIVE:  4519,
  HAS_TIMEWARPED_TAVERN_ALT_TEXT:  4579,
} as const;

/**
 * Render mechanic numeric IDs, sorted ascending.
 * These are the GAME_TAG enum IDs used as keys in renderModel.renderMechanics.
 *
 * Spec: [hearthstone-image-renderer-protocol](../../../../../docs/hearthstone-image-renderer-protocol.md)
 */
export const RENDER_MECHANIC_IDS = [
  String(TAG_ID.DATA_NUM_1),
  String(TAG_ID.DATA_NUM_2),
  String(TAG_ID.SCORE_VALUE_1),
  String(TAG_ID.MODULAR_ENTITY_PART_1),
  String(TAG_ID.MODULAR_ENTITY_PART_2),
  String(TAG_ID.QUEST_PROGRESS_TOTAL),
  String(TAG_ID.HIDE_HEALTH),
  String(TAG_ID.HIDE_ATTACK),
  String(TAG_ID.HIDE_COST),
  String(TAG_ID.HIDDEN_CHOICE),
  String(TAG_ID.USE_ALTERNATE_CARD_TEXT),
  String(TAG_ID.HIDE_WATERMARK),
  String(TAG_ID.BACON_TRIPLED_BASE_MINION_ID),
  String(TAG_ID.LETTUCE_PASSIVE_ABILITY),
  String(TAG_ID.LETTUCE_ABILITY_SUMMONED_MINION),
  String(TAG_ID.TRADEABLE),
  String(TAG_ID.IN_MINI_SET),
  String(TAG_ID.LETTUCE_MERCENARY_EXPERIENCE),
  String(TAG_ID.LETTUCE_EQUIPMENT),
  String(TAG_ID.LETTUCE_IS_TREASURE_CARD),
  String(TAG_ID.LETTUCE_ABILITY_TIER),
  String(TAG_ID.CARDTEXT_ENTITY_0),
  String(TAG_ID.CARDTEXT_ENTITY_1),
  String(TAG_ID.CARDTEXT_ENTITY_2),
  String(TAG_ID.CARDTEXT_ENTITY_3),
  String(TAG_ID.CARDTEXT_ENTITY_4),
  String(TAG_ID.CARDTEXT_ENTITY_5),
  String(TAG_ID.CARDTEXT_ENTITY_6),
  String(TAG_ID.CARDTEXT_ENTITY_7),
  String(TAG_ID.CARDTEXT_ENTITY_8),
  String(TAG_ID.CARDTEXT_ENTITY_9),
  String(TAG_ID.LETTUCE_EQUIPMENT_TIER),
  String(TAG_ID.FORGE),
  String(TAG_ID.DATA_NUM_3),
  String(TAG_ID.CARD_NAME_DATA_1),
  String(TAG_ID.DATA_NUM_4),
  String(TAG_ID.DATA_NUM_5),
  String(TAG_ID.DATA_NUM_6),
  String(TAG_ID.HIDDEN_CHOICE_OVERRIDE),
  String(TAG_ID.BACON_TRIPLED_BASE_MINION_ID2),
  String(TAG_ID.BACON_TRIPLED_BASE_MINION_ID3),
  String(TAG_ID.DYNAMIC_KEYWORD1),
  String(TAG_ID.DYNAMIC_KEYWORD2),
  String(TAG_ID.PREPARE),
  String(TAG_ID.TIMEWARPED),
  String(TAG_ID.BACON_ALT_TAVERN_SYSTEM_ACTIVE),
  String(TAG_ID.HAS_TIMEWARPED_TAVERN_ALT_TEXT),
] as const;
